### ISSUE TITLE
"e.cells is undefined" in uploaded ipynb files

### ISSUE THREAD

**Issue by chrysn** [jupyterlite/jupyterlite#1033]
## Description

When uploading a ipynb file (which was freshly downloaded) and opening it, a "File Load Error for (filename)" is shown, with the message "e.cells is undefined". The tab for the file flickers open only briefly, and is gone by the time the error is shown.

I've observed this both with Python (Pyodide) and JavaScript (Web Worker) notebooks.

## Reproduce

1. Go https://jupyterlite.readthedocs.io/en/latest/_static/lab/index.html
2. In the launcher, select a new Python or JavaScript notebook.
3. Right click on the file in the file browser tab, download it. (You could enter something and/or save it, makes no difference).
4. Close the file's tab.
5. Upload the file through the upload button in the file browser tab, confirm overwriting.
6. Double click on the (now re-uploaded) file.
7. See the error message.

## Context

I haven't observed this until today, and searching around in the issue tracker indicates this is new.

I've tried it with a freah browser instance.

- JupyterLite version: Whatever is currently running on jupyterlite.readthedocs.io (Help / About JupyterLite Examples shows 0.1.0-eta.22, but I don't think that's the relevant piece of info)
- Operating System and version: Debian sid (but I don't run anything locally, so it shouldn't matter)
- Browser and version: Firefox 111.0. uBlock Origin is running in the session that generated the output below, but I also tested with adblocking disabled.

<details><summary>Browser Output</summary>
<pre>
Unsatisfied version 6.0.2 from @jupyter-widgets/jupyterlab-manager of shared singleton module @jupyter-widgets/base (required ^1.1.10 || ^2 || ^3 || ^4.0.0) remoteEntry.03390b18ed36b245b514.js:1:6189
Unsatisfied version 6.0.2 of shared singleton module @jupyter-widgets/base (required ^1 || ^2 || ^3 || ^4) remoteEntry.8a3514e7c1c3c4a80f2e.js:1:5546
Unsatisfied version 6.0.2 of shared singleton module @jupyter-widgets/base (required ^1 || ^2 || ^3 || ^4) remoteEntry.0b6a37985538f1f2120b.js:1:5345
Registering new JupyterLite ServiceWorker https://jupyterlite.readthedocs.io/en/latest/_static/service-worker-b2fb40a.js service-manager.ts:50:16
JupyterLite ServiceWorker was sucessfully registered service-manager.ts:52:16
Kernel filesystem and JupyterLite contents will be synced index.ts:235:16
XHRGEThttps://jupyterlite.readthedocs.io/en/latest/_static/github?1680276910638
[HTTP/1.1 404 Not Found 0ms]

The JupyterLab GitHub server extension appears to be missing. If you do not install it with application credentials, you are likely to be rate limited by GitHub very quickly 784.7af3b56872a0f8721f0b.js:1:899
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://api.github.com/repos/jupyterlite/jupyterlite/contents? 784.7af3b56872a0f8721f0b.js:1:5275
DOMException: Node.removeChild: The node to be removed is not a child of this node index.ts:355:12
Using default public WebRTC signaling servers: not recommended for production. manager.js:160:16
GETwss://y-webrtc-signaling-us.herokuapp.com/

GETwss://signaling.yjs.dev/

Firefox can’t establish a connection to the server at wss://signaling.yjs.dev/. websocket.js:25:22
Firefox can’t establish a connection to the server at wss://y-webrtc-signaling-us.herokuapp.com/. websocket.js:25:22
GETwss://signaling.yjs.dev/

GETwss://y-webrtc-signaling-us.herokuapp.com/

Firefox can’t establish a connection to the server at wss://signaling.yjs.dev/. websocket.js:25:22
Pyodide contents will be synced with Jupyter Contents index.js:48:28
Starting WebSocket: wss://jupyterlite.readthedocs.io/en/latest/_static/api/kernels/7c520c54-eb96-4b0c-a5f5-b2c804035936 2 default.ts:1251:12
Firefox can’t establish a connection to the server at wss://y-webrtc-signaling-us.herokuapp.com/. websocket.js:25:22
Starting WebSocket: wss://jupyterlite.readthedocs.io/en/latest/_static/api/kernels/7c520c54-eb96-4b0c-a5f5-b2c804035936 default.ts:1251:12
WebSocket connection to 'wss://signaling.yjs.dev/' failed mock-socket.js:704:20
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://cdn.jsdelivr.net/pyodide/v0.22.0/full/pyodide_py.tar pyodide_py.tar
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://cdn.jsdelivr.net/pyodide/v0.22.0/full/pyodide.asm.data pyodide.asm.data
WebSocket connection to 'wss://y-webrtc-signaling-us.herokuapp.com/' failed mock-socket.js:704:20
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://cdn.jsdelivr.net/pyodide/v0.22.0/full/repodata.json repodata.json
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://cdn.jsdelivr.net/pyodide/v0.22.0/full/pyodide.asm.wasm pyodide.asm.wasm
WebSocket connection to 'wss://signaling.yjs.dev/' failed mock-socket.js:704:20
WebSocket connection to 'wss://y-webrtc-signaling-us.herokuapp.com/' failed mock-socket.js:704:20
WebSocket connection to 'wss://signaling.yjs.dev/' failed mock-socket.js:704:20
WebSocket connection to 'wss://y-webrtc-signaling-us.herokuapp.com/' failed mock-socket.js:704:20
WebSocket connection to 'wss://signaling.yjs.dev/' failed mock-socket.js:704:20
WebSocket connection to 'wss://y-webrtc-signaling-us.herokuapp.com/' failed mock-socket.js:704:20
WebSocket connection to 'wss://signaling.yjs.dev/' failed mock-socket.js:704:20
Failed to fetch ipywidgets through the "jupyter.widget.control" comm channel, fallback to fetching individual model state. Reason: Control comm did not respond in time 150.b0e841b75317744a7595.js:1:5783
WebSocket connection to 'wss://y-webrtc-signaling-us.herokuapp.com/' failed mock-socket.js:704:20
Loading micropip, pyparsing, packaging pyodide.asm.js:10:144854
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://cdn.jsdelivr.net/pyodide/v0.22.0/full/micropip-0.2.0-py3-none-any.whl micropip-0.2.0-py3-none-any.whl
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://cdn.jsdelivr.net/pyodide/v0.22.0/full/pyparsing-3.0.9-py3-none-any.whl pyparsing-3.0.9-py3-none-any.whl
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://cdn.jsdelivr.net/pyodide/v0.22.0/full/packaging-21.3-py3-none-any.whl packaging-21.3-py3-none-any.whl
Loaded pyparsing, packaging, micropip pyodide.asm.js:10:145216
WebSocket connection to 'wss://signaling.yjs.dev/' failed mock-socket.js:704:20
WebSocket connection to 'wss://y-webrtc-signaling-us.herokuapp.com/' failed mock-socket.js:704:20
Loading sqlite3 pyodide.asm.js:10:144854
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://cdn.jsdelivr.net/pyodide/v0.22.0/full/sqlite3-1.0.0.zip sqlite3-1.0.0.zip
Loaded sqlite3 pyodide.asm.js:10:145216
WebSocket connection to 'wss://signaling.yjs.dev/' failed mock-socket.js:704:20
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://pypi.org/pypi/ipython/json json
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://files.pythonhosted.org/packages/9d/1c/6001840eceb489e4a3e6ae9b012cb56b109dd6b8ee286d7771166b83d111/ipython-8.12.0-py3-none-any.whl ipython-8.12.0-py3-none-any.whl
WebSocket connection to 'wss://y-webrtc-signaling-us.herokuapp.com/' failed mock-socket.js:704:20
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://pypi.org/pypi/stack-data/json json
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://pypi.org/pypi/pickleshare/json json
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://pypi.org/pypi/matplotlib-inline/json json
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://pypi.org/pypi/prompt-toolkit/json json
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://pypi.org/pypi/pexpect/json json
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://pypi.org/pypi/traitlets/json json
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://pypi.org/pypi/backcall/json json
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://files.pythonhosted.org/packages/6a/81/aa96c25c27f78cdc444fec27d80f4c05194c591465e491a1358d8a035bc1/stack_data-0.6.2-py3-none-any.whl stack_data-0.6.2-py3-none-any.whl
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://files.pythonhosted.org/packages/87/3f/1f5a0ff475ae6481f4b0d45d4d911824d3218b94ee2a97a8cb84e5569836/prompt_toolkit-3.0.38-py3-none-any.whl prompt_toolkit-3.0.38-py3-none-any.whl
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://files.pythonhosted.org/packages/f2/51/c34d7a1d528efaae3d8ddb18ef45a41f284eacf9e514523b191b7d0872cc/matplotlib_inline-0.1.6-py3-none-any.whl matplotlib_inline-0.1.6-py3-none-any.whl
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://files.pythonhosted.org/packages/9a/41/220f49aaea88bc6fa6cba8d05ecf24676326156c23b991e80b3f2fc24c77/pickleshare-0.7.5-py2.py3-none-any.whl pickleshare-0.7.5-py2.py3-none-any.whl
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://files.pythonhosted.org/packages/77/75/c28e9ef7abec2b7e9ff35aea3e0be6c1aceaf7873c26c95ae1f0d594de71/traitlets-5.9.0-py3-none-any.whl traitlets-5.9.0-py3-none-any.whl
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://files.pythonhosted.org/packages/39/7b/88dbb785881c28a102619d46423cb853b46dbccc70d3ac362d99773a78ce/pexpect-4.8.0-py2.py3-none-any.whl pexpect-4.8.0-py2.py3-none-any.whl
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://files.pythonhosted.org/packages/4c/1c/ff6546b6c12603d8dd1070aa3c3d273ad4c07f5771689a7b69a550e8c951/backcall-0.2.0-py2.py3-none-any.whl backcall-0.2.0-py2.py3-none-any.whl
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://pypi.org/pypi/asttokens/json json
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://pypi.org/pypi/pure-eval/json json
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://pypi.org/pypi/executing/json json
WebSocket connection to 'wss://signaling.yjs.dev/' failed mock-socket.js:704:20
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://files.pythonhosted.org/packages/2b/27/77f9d5684e6bce929f5cfe18d6cfbe5133013c06cb2fbf5933670e60761d/pure_eval-0.2.2-py3-none-any.whl pure_eval-0.2.2-py3-none-any.whl
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://files.pythonhosted.org/packages/f3/e1/64679d9d0759db5b182222c81ff322c2fe2c31e156a59afd6e9208c960e5/asttokens-2.2.1-py2.py3-none-any.whl asttokens-2.2.1-py2.py3-none-any.whl
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://files.pythonhosted.org/packages/28/3c/bc3819dd8b1a1588c9215a87271b6178cc5498acaa83885211f5d4d9e693/executing-1.2.0-py2.py3-none-any.whl executing-1.2.0-py2.py3-none-any.whl
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://pypi.org/pypi/ptyprocess/json json
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://pypi.org/pypi/wcwidth/json json
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://files.pythonhosted.org/packages/20/f4/c0584a25144ce20bfcf1aecd041768b8c762c1eb0aa77502a3f0baa83f11/wcwidth-0.2.6-py2.py3-none-any.whl wcwidth-0.2.6-py2.py3-none-any.whl
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://files.pythonhosted.org/packages/22/a6/858897256d0deac81a172289110f31629fc4cee19b6f01283303e18c8db3/ptyprocess-0.7.0-py2.py3-none-any.whl ptyprocess-0.7.0-py2.py3-none-any.whl
Loading pygments, decorator, jedi, parso, six pyodide.asm.js:10:144854
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://cdn.jsdelivr.net/pyodide/v0.22.0/full/Pygments-2.13.0-py3-none-any.whl Pygments-2.13.0-py3-none-any.whl
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://cdn.jsdelivr.net/pyodide/v0.22.0/full/decorator-5.1.1-py3-none-any.whl decorator-5.1.1-py3-none-any.whl
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://cdn.jsdelivr.net/pyodide/v0.22.0/full/jedi-0.18.2-py2.py3-none-any.whl jedi-0.18.2-py2.py3-none-any.whl
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://cdn.jsdelivr.net/pyodide/v0.22.0/full/parso-0.8.3-py2.py3-none-any.whl parso-0.8.3-py2.py3-none-any.whl
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://cdn.jsdelivr.net/pyodide/v0.22.0/full/six-1.16.0-py2.py3-none-any.whl six-1.16.0-py2.py3-none-any.whl
WebSocket connection to 'wss://y-webrtc-signaling-us.herokuapp.com/' failed mock-socket.js:704:20
WebSocket connection to 'wss://signaling.yjs.dev/' failed mock-socket.js:704:20
WebSocket connection to 'wss://y-webrtc-signaling-us.herokuapp.com/' failed mock-socket.js:704:20
Loaded decorator, six, parso, pygments, jedi pyodide.asm.js:10:145216
WebSocket connection to 'wss://signaling.yjs.dev/' failed mock-socket.js:704:20
WebSocket connection to 'wss://y-webrtc-signaling-us.herokuapp.com/' failed mock-socket.js:704:20
WebSocket connection to 'wss://signaling.yjs.dev/' failed mock-socket.js:704:20
WebSocket connection to 'wss://y-webrtc-signaling-us.herokuapp.com/' failed mock-socket.js:704:20
WebSocket connection to 'wss://signaling.yjs.dev/' failed mock-socket.js:704:20
WebSocket connection to 'wss://y-webrtc-signaling-us.herokuapp.com/' failed mock-socket.js:704:20
WebSocket connection to 'wss://signaling.yjs.dev/' failed mock-socket.js:704:20
WebSocket connection to 'wss://y-webrtc-signaling-us.herokuapp.com/' failed mock-socket.js:704:20
WebSocket connection to 'wss://signaling.yjs.dev/' failed mock-socket.js:704:20
WebSocket connection to 'wss://y-webrtc-signaling-us.herokuapp.com/' failed mock-socket.js:704:20
WebSocket connection to 'wss://signaling.yjs.dev/' failed mock-socket.js:704:20
WebSocket connection to 'wss://y-webrtc-signaling-us.herokuapp.com/' failed mock-socket.js:704:20
WebSocket connection to 'wss://signaling.yjs.dev/' failed mock-socket.js:704:20
WebSocket connection to 'wss://y-webrtc-signaling-us.herokuapp.com/' failed mock-socket.js:704:20
WebSocket connection to 'wss://signaling.yjs.dev/' failed mock-socket.js:704:20
WebSocket connection to 'wss://y-webrtc-signaling-us.herokuapp.com/' failed mock-socket.js:704:20
WebSocket connection to 'wss://signaling.yjs.dev/' failed mock-socket.js:704:20
WebSocket connection to 'wss://y-webrtc-signaling-us.herokuapp.com/' failed mock-socket.js:704:20
WebSocket connection to 'wss://signaling.yjs.dev/' failed mock-socket.js:704:20
WebSocket connection to 'wss://y-webrtc-signaling-us.herokuapp.com/' failed mock-socket.js:704:20
WebSocket connection to 'wss://signaling.yjs.dev/' failed mock-socket.js:704:20
TypeError: e.value is undefined
    _setValue jsoneditor.ts:331
    set source jsoneditor.ts:134
    _update notebooktools.ts:637
    onActiveNotebookPanelChanged notebooktools.ts:623
    processMessage notebooktools.ts:345
    c index.ts:530
    e index.ts:220
    _onActiveNotebookPanelChanged notebooktools.ts:172
    f iter.ts:227
    _onActiveNotebookPanelChanged notebooktools.ts:171
    u index.ts:679
    emit index.ts:600
    emit index.ts:212
    A widgettracker.ts:135
    u index.ts:679
    emit index.ts:600
    emit index.ts:212
    _onInstanceDisposed restorablepool.ts:314
    u index.ts:679
    emit index.ts:600
    emit index.ts:212
    dispose widget.ts:68
    dispose panel.ts:150
    _revealed mainareawidget.ts:78
    u index.ts:679
    emit index.ts:600
    emit index.ts:212
    dispose widget.ts:68
    dispose widget.ts:379
    dispose widget.ts:1328
    dispose panel.ts:149
    onClose widgetmanager.ts:318
    messageHook widgetmanager.ts:232
    o index.ts:515
    o index.ts:226
    c iter.ts:266
    e index.ts:225
    close widget.ts:410
    _onTabCloseRequested dockpanel.ts:1031
    u index.ts:679
    emit index.ts:600
    emit index.ts:212
    _evtMouseUp tabbar.ts:978
    handleEvent tabbar.ts:609
    _evtMouseDown tabbar.ts:793
    handleEvent tabbar.ts:603
    onBeforeAttach tabbar.ts:629
    processMessage widget.ts:557
    c index.ts:530
    e index.ts:220
    attachWidget docklayout.ts:558
    _createTabBar docklayout.ts:1115
    _insertTab docklayout.ts:826
    addWidget docklayout.ts:408
    addWidget dockpanel.ts:407
    _addToMainArea shell.ts:1134
    add shell.ts:763
    execute index.ts:84
    execute index.ts:437
    createLauncher index.ts:1215
    e index.ts:467
    activate index.ts:495
    promise callback*activate index.ts:460
    promise index.ts:329
    promise callback*61278/t.prototype.activatePlugin/d</< index.ts:329
    u tslib.es6.js:102
    u tslib.es6.js:83
    u tslib.es6.js:76
    u tslib.es6.js:72
    activatePlugin index.ts:304
    r index.ts:517
    start index.ts:516
    f index.js:579
index.ts:467:12
WebSocket connection to 'wss://y-webrtc-signaling-us.herokuapp.com/' failed mock-socket.js:704:20
WebSocket connection to 'wss://signaling.yjs.dev/' failed mock-socket.js:704:20
WebSocket connection to 'wss://y-webrtc-signaling-us.herokuapp.com/' failed mock-socket.js:704:20
WebSocket connection to 'wss://signaling.yjs.dev/' failed mock-socket.js:704:20
WebSocket connection to 'wss://y-webrtc-signaling-us.herokuapp.com/' failed mock-socket.js:704:20
WebSocket connection to 'wss://signaling.yjs.dev/' failed mock-socket.js:704:20
WebSocket connection to 'wss://y-webrtc-signaling-us.herokuapp.com/' failed mock-socket.js:704:20
WebSocket connection to 'wss://signaling.yjs.dev/' failed mock-socket.js:704:20
WebSocket connection to 'wss://y-webrtc-signaling-us.herokuapp.com/' failed mock-socket.js:704:20
WebSocket connection to 'wss://signaling.yjs.dev/' failed mock-socket.js:704:20
WebSocket connection to 'wss://y-webrtc-signaling-us.herokuapp.com/' failed mock-socket.js:704:20
WebSocket connection to 'wss://signaling.yjs.dev/' failed mock-socket.js:704:20
Using default public WebRTC signaling servers: not recommended for production. manager.js:160:16
TypeError: e.value is undefined
    _setValue jsoneditor.ts:331
    set source jsoneditor.ts:134
    _update notebooktools.ts:672
    onActiveCellChanged notebooktools.ts:660
    processMessage notebooktools.ts:348
    c index.ts:530
    e index.ts:220
    _onActiveCellChanged notebooktools.ts:195
    f iter.ts:227
    _onActiveCellChanged notebooktools.ts:194
    u index.ts:679
    emit index.ts:600
    emit index.ts:212
    onCurrentChanged tracker.ts:82
    A widgettracker.ts:131
    u index.ts:679
    emit index.ts:600
    emit index.ts:212
    set current restorablepool.ts:61
    add widgettracker.ts:197
    add tracker.ts:52
    activate index.ts:1356
    u index.ts:679
    emit index.ts:600
    emit index.ts:212
    createNew default.ts:428
    createWidget widgetmanager.ts:73
    _createOrOpenDocument manager.ts:600
    open manager.ts:365
    openOrReveal manager.ts:401
    handleOpen listing.ts:1021
    evtDblClick listing.ts:1116
    handleEvent listing.ts:666
    onAfterAttach listing.ts:711
    processMessage widget.ts:565
    c index.ts:530
    e index.ts:220
    attachWidget panellayout.ts:218
    insertWidget panellayout.ts:105
    addWidget panellayout.ts:69
    set useFuzzyFilter browser.ts:189
    r index.ts:238
    activate index.ts:247
    promise callback*59806/activate/< index.ts:216
    promise callback*activate index.ts:206
    promise index.ts:329
    promise callback*61278/t.prototype.activatePlugin/d</< index.ts:329
    u tslib.es6.js:102
    u tslib.es6.js:83
    u tslib.es6.js:76
    u tslib.es6.js:72
    activatePlugin index.ts:304
    r index.ts:517
    start index.ts:516
    f index.js:579
index.ts:467:12
WebSocket connection to 'wss://y-webrtc-signaling-us.herokuapp.com/' failed mock-socket.js:704:20
Showing error: TypeError: e.cells is undefined
    fromJSON model.ts:293
    _revert context.ts:683
    promise callback*_revert context.ts:678
    initialize context.ts:269
    c manager.ts:590
    promise callback*_createOrOpenDocument manager.ts:590
    open manager.ts:365
    openOrReveal manager.ts:401
    handleOpen listing.ts:1021
    evtDblClick listing.ts:1116
    handleEvent listing.ts:666
    onAfterAttach listing.ts:711
    processMessage widget.ts:565
    c index.ts:530
    e index.ts:220
    attachWidget panellayout.ts:218
    insertWidget panellayout.ts:105
    addWidget panellayout.ts:69
    set useFuzzyFilter browser.ts:189
    r index.ts:238
    activate index.ts:247
    promise callback*59806/activate/< index.ts:216
    promise callback*activate index.ts:206
    promise index.ts:329
    promise callback*61278/t.prototype.activatePlugin/d</< index.ts:329
    u tslib.es6.js:102
    u tslib.es6.js:83
    u tslib.es6.js:76
    u tslib.es6.js:72
    activatePlugin index.ts:304
    r index.ts:517
    start index.ts:516
    f index.js:579
widgettracker.ts:329:16
Failed to initialize the context with 'notebook' for Untitled.ipynb TypeError: e.cells is undefined
    fromJSON model.ts:293
    _revert context.ts:683
    promise callback*_revert context.ts:678
    initialize context.ts:269
    c manager.ts:590
    promise callback*_createOrOpenDocument manager.ts:590
    open manager.ts:365
    openOrReveal manager.ts:401
    handleOpen listing.ts:1021
    evtDblClick listing.ts:1116
    handleEvent listing.ts:666
    onAfterAttach listing.ts:711
    processMessage widget.ts:565
    c index.ts:530
    e index.ts:220
    attachWidget panellayout.ts:218
    insertWidget panellayout.ts:105
    addWidget panellayout.ts:69
    set useFuzzyFilter browser.ts:189
    r index.ts:238
    activate index.ts:247
    promise callback*59806/activate/< index.ts:216
    promise callback*activate index.ts:206
    promise index.ts:329
    promise callback*61278/t.prototype.activatePlugin/d</< index.ts:329
    u tslib.es6.js:102
    u tslib.es6.js:83
    u tslib.es6.js:76
    u tslib.es6.js:72
    activatePlugin index.ts:304
    r index.ts:517
    start index.ts:516
    f index.js:579
6898.9bbc12a.js:1:13106
TypeError: e.value is undefined
    _setValue jsoneditor.ts:331
    set source jsoneditor.ts:134
    _update notebooktools.ts:637
    onActiveNotebookPanelChanged notebooktools.ts:623
    processMessage notebooktools.ts:345
    c index.ts:530
    e index.ts:220
    _onActiveNotebookPanelChanged notebooktools.ts:172
    f iter.ts:227
    _onActiveNotebookPanelChanged notebooktools.ts:171
    u index.ts:679
    emit index.ts:600
    emit index.ts:212
    A widgettracker.ts:135
    u index.ts:679
    emit index.ts:600
    emit index.ts:212
    _onInstanceDisposed restorablepool.ts:314
    u index.ts:679
    emit index.ts:600
    emit index.ts:212
    dispose widget.ts:68
    dispose panel.ts:150
    onClose widgetmanager.ts:318
    messageHook widgetmanager.ts:232
    o index.ts:515
    o index.ts:226
    c iter.ts:266
    e index.ts:225
    close widget.ts:410
    _createOrOpenDocument manager.ts:609
    promise callback*_createOrOpenDocument manager.ts:604
    open manager.ts:365
    openOrReveal manager.ts:401
    handleOpen listing.ts:1021
    evtDblClick listing.ts:1116
    handleEvent listing.ts:666
    onAfterAttach listing.ts:711
    processMessage widget.ts:565
    c index.ts:530
    e index.ts:220
    attachWidget panellayout.ts:218
    insertWidget panellayout.ts:105
    addWidget panellayout.ts:69
    set useFuzzyFilter browser.ts:189
    r index.ts:238
    activate index.ts:247
    promise callback*59806/activate/< index.ts:216
    promise callback*activate index.ts:206
    promise index.ts:329
    promise callback*61278/t.prototype.activatePlugin/d</< index.ts:329
    u tslib.es6.js:102
    u tslib.es6.js:83
    u tslib.es6.js:76
    u tslib.es6.js:72
    activatePlugin index.ts:304
    r index.ts:517
    start index.ts:516
    f index.js:579
index.ts:467:12
WebSocket connection to 'wss://signaling.yjs.dev/' failed mock-socket.js:704:20
WebSocket connection to 'wss://y-webrtc-signaling-us.herokuapp.com/' failed mock-socket.js:704:20
WebSocket connection to 'wss://signaling.yjs.dev/' failed mock-socket.js:704:20
WebSocket connection to 'wss://y-webrtc-signaling-us.herokuapp.com/' failed mock-socket.js:704:20
WebSocket connection to 'wss://signaling.yjs.dev/' failed mock-socket.js:704:20
WebSocket connection to 'wss://y-webrtc-signaling-us.herokuapp.com/' failed mock-socket.js:704:20

</pre>
</details>

**Comment by jtpio** [comment]
Thanks @chrysn for reporting. I'll have a look.

**Comment by jtpio** [comment]
Looking into this in https://github.com/jupyterlite/jupyterlite/pull/1034.
