### ISSUE TITLE
error when running initial cli build with `jupyterlite-core`

### ISSUE THREAD

**Issue by stevejpurves** [jupyterlite/jupyterlite#1037]
## Description

I am initialising and building a new standalone site [as per the docs](https://jupyterlite.readthedocs.io/en/latest/quickstart/standalone.html) but keep hitting an error

```
.  build:lite:patch:_output/jupyter-lite.json
TaskError - taskid:build:lite:patch:_output/jupyter-lite.json
PythonAction Error
Traceback (most recent call last):
  File "/Users/stevejpurves/dev/jlite/env/lib/python3.9/site-packages/doit/action.py", line 461, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/Users/stevejpurves/dev/jlite/env/lib/python3.9/site-packages/jupyterlite_core/addons/base.py", line 240, in merge_one_jupyterlite
    out_path.write_text(json.dumps(config, **JSON_FMT), **UTF8)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/pathlib.py", line 1285, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors) as f:
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/stevejpurves/dev/jlite/dist/_output/jupyter-lite.json'
```

## Reproduce

1. Create a clear `venv` `python -m venv install env`
2. activate it
3. `python -m pip install jupyter jupyterlab`
4. `python -m pip install jupyterlite-core`
5. in an empty folder
6. `jupyter lite init`
7. `jupyter lite build --output-dir dist`

```
static:jupyter-lite.json
.  pre_status:static:jupyter-lite.json
    tarball:         jupyterlite-app-0.1.0-rc.0.tgz 7MB
    output:          /Users/stevejpurves/dev/jlite/dist
    lite dir:        /Users/stevejpurves/dev/jlite
    apps:            
    sourcemaps:      True
    unused packages: True
archive:archive
contents:contents
lite:jupyter-lite.json
mathjax:status
mimetypes:jupyter-lite.json
serve:contents
settings:overrides
translation:translation
.  status:archive:archive
[LiteBuildApp] No archive (yet): jlite-jupyterlite.tgz
.  status:contents:contents
    contents: 0 files
.  status:lite:jupyter-lite.json
[LiteBuildApp]     jupyter-lite.(json|ipynb): 16 files
.  status:mathjax:status
     jupyter-server-mathjax: None 
     configured MathJax dir: /Users/stevejpurves/dev/jlite/traitlets.Undefined
     effective MathJax dir: None
.  status:mimetypes:jupyter-lite.json
    filetypes:         26 
.  status:serve:contents
    url: http://127.0.0.1:8000/
    server: tornado
    headers:
.  status:settings:overrides
    overrides.json: 0
.  status:translation:translation
    translation files: 0 files
static:output_dir
-- pre_init:static:output_dir
static:unpack
-- init:static:unpack
federated_extensions:copy:ext:jupyterlab_pygments
federated_extensions:copy:ext:@jupyter-widgets/jupyterlab-manager
-- pre_build:federated_extensions:copy:ext:jupyterlab_pygments
-- pre_build:federated_extensions:copy:ext:@jupyter-widgets/jupyterlab-manager
lite:patch:_output/jupyter-lite.json
lite:patch:_output/lab/jupyter-lite.json
lite:patch:_output/repl/jupyter-lite.json
lite:patch:_output/retro/jupyter-lite.json
lite:patch:_output/retro/tree/jupyter-lite.json
lite:patch:_output/retro/edit/jupyter-lite.json
lite:patch:_output/retro/consoles/jupyter-lite.json
lite:patch:_output/retro/notebooks/jupyter-lite.json
lite:patch:_output/jupyter-lite.ipynb
lite:patch:_output/lab/jupyter-lite.ipynb
lite:patch:_output/repl/jupyter-lite.ipynb
lite:patch:_output/retro/jupyter-lite.ipynb
lite:patch:_output/retro/tree/jupyter-lite.ipynb
lite:patch:_output/retro/edit/jupyter-lite.ipynb
lite:patch:_output/retro/consoles/jupyter-lite.ipynb
lite:patch:_output/retro/notebooks/jupyter-lite.ipynb
translation:copy
.  build:lite:patch:_output/jupyter-lite.json
TaskError - taskid:build:lite:patch:_output/jupyter-lite.json
PythonAction Error
Traceback (most recent call last):
  File "/Users/stevejpurves/dev/jlite/env/lib/python3.9/site-packages/doit/action.py", line 461, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/Users/stevejpurves/dev/jlite/env/lib/python3.9/site-packages/jupyterlite_core/addons/base.py", line 240, in merge_one_jupyterlite
    out_path.write_text(json.dumps(config, **JSON_FMT), **UTF8)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/pathlib.py", line 1285, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors) as f:
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/stevejpurves/dev/jlite/dist/_output/jupyter-lite.json'
```

8. `jupyter lite serve` then produces a different error with a slightly different path

```
translation:copy
.  build:lite:patch:_output/jupyter-lite.json
TaskError - taskid:build:lite:patch:_output/jupyter-lite.json
PythonAction Error
Traceback (most recent call last):
  File "/Users/stevejpurves/dev/jlite/env/lib/python3.9/site-packages/doit/action.py", line 461, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/Users/stevejpurves/dev/jlite/env/lib/python3.9/site-packages/jupyterlite_core/addons/base.py", line 240, in merge_one_jupyterlite
    out_path.write_text(json.dumps(config, **JSON_FMT), **UTF8)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/pathlib.py", line 1285, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors) as f:
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/stevejpurves/dev/jlite/dist/_output/jupyter-lite.json'
```

## Expected

The command should complete without error

## Context

- JupyterLite version: 0.1.0-rc.0
- Operating System and version: macos 12.6
- Browser and version: n/a

**Comment by stevejpurves** [comment]
Note if I delete the `doit.db` and `_output` folder and start over without the `--output-dir` option, then the `init`, `build` and `serve` commands all work without error.

**Comment by jtpio** [comment]
Thanks @stevejpurves for reporting :+1: 

Right it could be `doit` getting confused about its cache.

This also seems to be related to https://github.com/jupyterlite/jupyterlite/issues/718.

**Comment by maartenbreddels** [comment]
I also randomly get this, an rm -rf seems to sometimes fix it.
