### ISSUE TITLE
Pyodide kernel : status unknown with Edge

### ISSUE THREAD

**Issue by guiguichau** [jupyterlite/jupyterlite#1179]
## Description
Hi guys. Any help would be apreciated. Thanks in advance

I open  : https://jupyter.org/try-jupyter/lab/?path=notebooks%2FIntro.ipynb
The Pydodide kernel stays in unknown status even after restarting the kernel. (The SQL Lite kernel is working)
I deleted cookies, cache... with no success
I also tried in a InPrivate window. 
## Context

- JupyterLite version: 0.1.2
- Operating System and version: Windows 10 Pro
- Browser and version: Edge Version 117.0.2045.43 (Version officielle) (64 bits)

<details><summary>Browser Output</summary>
<pre>
Output from your browser Javascript console here.

﻿
manifest.webmanifest:1 
 Manifest: property 'url' ignored, should be within scope of the manifest.
manifest.webmanifest:1 
 Manifest: property 'url' of 'shortcut' not present.
manifest.webmanifest:1 
 Manifest: property 'url' ignored, should be within scope of the manifest.
manifest.webmanifest:1 
 Manifest: property 'url' of 'shortcut' not present.
remoteEntry.a37e37c….js:1 
 Unsatisfied version 1.37.1 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @lumino/widgets (required ^2.0.1)
remoteEntry.a37e37c….js:1 
 Unsatisfied version 1.10.3 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @lumino/messaging (required ^2.0.0)
remoteEntry.a37e37c….js:1 
 Unsatisfied version 1.12.1 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @lumino/coreutils (required ^2.0.0)
remoteEntry.a37e37c….js:1 
 Unsatisfied version 1.11.1 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @lumino/signaling (required ^2.0.0)
remoteEntry.a37e37c….js:1 
 Unsatisfied version 1.9.2 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @lumino/algorithm (required ^2.0.0)
remoteEntry.a37e37c….js:1 
 Unsatisfied version 3.5.3 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/translation (required ^4.0.5)
remoteEntry.a37e37c….js:1 
 Unsatisfied version 3.5.3 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/settingregistry (required ^4.0.5)
remoteEntry.a37e37c….js:1 
 Unsatisfied version 3.5.3 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/notebook (required ^4.0.5)
remoteEntry.a37e37c….js:1 
 Unsatisfied version 6.5.3 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/services (required ^7.0.5)
remoteEntry.a37e37c….js:1 
 Unsatisfied version 1.8.2 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @lumino/properties (required ^2.0.0)
remoteEntry.a37e37c….js:1 
 No satisfying version (^4.0.5) of shared module @jupyterlab/outputarea found in shared scope default.
Available versions: 3.5.3 from _JUPYTERLAB.CORE_OUTPUT
remoteEntry.a37e37c….js:1 
 Unsatisfied version 3.5.3 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/logconsole (required ^4.0.5)
remoteEntry.a37e37c….js:1 
 Unsatisfied version 3.5.3 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/rendermime (required ^4.0.5)
remoteEntry.a37e37c….js:1 
 Unsatisfied version 1.10.4 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @lumino/disposable (required ^2.0.0)
remoteEntry.a37e37c….js:1 
 Unsatisfied version 3.5.3 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/mainmenu (required ^4.0.5)
remoteEntry.b15a25c….js:1 
 Unsatisfied version 1.37.1 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @lumino/widgets (required ^2.0.1)
remoteEntry.6a76d3e….js:1 
 Unsatisfied version 3.5.3 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/apputils (required ^4.0.0)
remoteEntry.6a76d3e….js:1 
 Unsatisfied version 1.9.2 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @lumino/algorithm (required ^2.0.0)
remoteEntry.6a76d3e….js:1 
 Unsatisfied version 1.37.1 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @lumino/widgets (required ^2.0.1)
remoteEntry.6a76d3e….js:1 
 Unsatisfied version 3.5.3 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/ui-components (required ^4.0.0)
remoteEntry.ade7222….js:1 
 Unsatisfied version 1.37.1 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @lumino/widgets (required ^1.37.2)
remoteEntry.edc72ee….js:1 
 Unsatisfied version 1.37.1 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @lumino/widgets (required ^1.37.2)
remoteEntry.74a3757….js:1 
 Unsatisfied version 5.5.3 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/coreutils (required ^5.6.3)
remoteEntry.74a3757….js:1 
 Unsatisfied version 3.5.3 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/application (required ^3.6.3)
remoteEntry.d50eb71….js:1 
 Unsatisfied version 1.37.1 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @lumino/widgets (required ^1.37.2)
service-manager.ts:50 Registering new JupyterLite ServiceWorker https://jupyter.org/try-jupyter/service-worker-f7de73d.js
service-manager.ts:52 JupyterLite ServiceWorker was sucessfully registered
index.ts:235 Kernel filesystem and JupyterLite contents will be synced
index.js:51 Pyodide contents will be synced with Jupyter Contents
pyodide.asm.js:9 Loading micropip, packaging
pyodide.asm.js:9 Loaded packaging, micropip
pyodide.asm.js:9 Loading sqlite3
pyodide.asm.js:9 Loaded sqlite3
336.ebc7a55ea1768712…7a55ea1768712771f:1 
 Failed to fetch ipywidgets through the "jupyter.widget.control" comm channel, fallback to fetching individual model state. Reason: Control comm did not respond in time
kernel.js:40 
 Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python311.zip/_pyodide/_base.py", line 571, in eval_code_async
    await CodeRunner(
  File "/lib/python311.zip/_pyodide/_base.py", line 396, in run_async
    await coroutine
  File "<exec>", line 4, in <module>
  File "/lib/python3.11/site-packages/piplite/piplite.py", line 116, in _install
    return await micropip.install(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/micropip/_commands/install.py", line 138, in install
    await transaction.gather_requirements(requirements)
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 197, in gather_requirements
    await asyncio.gather(*requirement_promises)
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 204, in add_requirement
    return await self.add_requirement_inner(Requirement(req))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 319, in add_requirement_inner
    await self.add_wheel(wheel, req.extras, specifier=str(req.specifier))
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 355, in add_wheel
    await wheel.download(self.fetch_kwargs)
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 98, in download
    data = await self._fetch_bytes(fetch_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 88, in _fetch_bytes
    raise e
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 82, in _fetch_bytes
    return await fetch_bytes(self.url, fetch_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/micropip/_compat_in_pyodide.py", line 30, in fetch_bytes
    result_bytes = await (await pyfetch(url, **kwargs)).bytes()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python311.zip/pyodide/http.py", line 308, in pyfetch
    raise OSError(e.message) from None
OSError: Failed to fetch

    at new_error (cdn.jsdelivr.net/pyo…dide.asm.js:9:12519)
    at cdn.jsdelivr.net/pyo…ll/pyodide.asm.wasm
    at cdn.jsdelivr.net/pyo…ll/pyodide.asm.wasm
    at _PyCFunctionWithKeywords_TrampolineCall (cdn.jsdelivr.net/pyo…ide.asm.js:9:123040)
    at cdn.jsdelivr.net/pyo…ll/pyodide.asm.wasm
    at cdn.jsdelivr.net/pyo…ll/pyodide.asm.wasm
    at cdn.jsdelivr.net/pyo…ll/pyodide.asm.wasm
    at cdn.jsdelivr.net/pyo…ll/pyodide.asm.wasm
    at cdn.jsdelivr.net/pyo…ll/pyodide.asm.wasm
    at cdn.jsdelivr.net/pyo…ll/pyodide.asm.wasm
    at cdn.jsdelivr.net/pyo…ll/pyodide.asm.wasm
    at cdn.jsdelivr.net/pyo…ll/pyodide.asm.wasm
    at cdn.jsdelivr.net/pyo…ll/pyodide.asm.wasm
    at cdn.jsdelivr.net/pyo…ll/pyodide.asm.wasm
    at cdn.jsdelivr.net/pyo…ll/pyodide.asm.wasm
    at Module.callPyObjectKwargs (cdn.jsdelivr.net/pyo…dide.asm.js:9:81732)
    at Module.callPyObject (cdn.jsdelivr.net/pyo…dide.asm.js:9:82066)
    at wrapper (cdn.jsdelivr.net/pyo…dide.asm.js:9:58562)

**Comment by jtpio** [comment]
@guiguichau would you be able to try again? This JupyterLite was updated to the latest packages so maybe that would fix your issue?

Looking fine when testing in a Firefox private window:

![image](https://github.com/jupyterlite/jupyterlite/assets/591645/79ace656-4f34-46d9-ba85-a35ba040aed4)

**Comment by guiguichau** [comment]
Hi @jtpio 
Thanks a lot for your reply. It still does not work even in a private window (I can only use Edge).
Have a nice day.
