### ISSUE TITLE
Opening a notebook from a URL with an encoded space character in it is broken

### ISSUE THREAD

**Issue by tomjakubowski** [jupyterlite/jupyterlite#1211]
## Description

I wanted to try my friend's ipynb in Jupyterlite. It was published on GitHub, so I added it from the File -> Open from URL menu.

When I did that, a file was added to my local Jupyterlite filesystem. But I wasn't able to open it - instead, I got this error message.

<img width="468" alt="Screenshot 2023-10-13 at 12 46 42 PM" src="https://github.com/jupyterlite/jupyterlite/assets/667901/d2862a86-e797-4e78-944d-1b8aead555a7">

## Reproduce

1. Go to https://jupyterlite.readthedocs.io/en/stable/_static/lab/index.html
2. File -> Open from URL
3. Open my friend's notebook https://raw.githubusercontent.com/mds2/rocketry/main/rocket%20equations.ipynb 

## Expected behavior

The notebook is added and I can open it.

## Context

- JupyterLite version: Version 0.1.3
- Operating System and version: macOS 13.3.1
- Browser and version: Chrome 117

<details><summary>Browser Output</summary>
<pre>
dialog.tsx:43 Showing error: Error: Could not find file with path rocket%20equations.ipynb
    at m.createCheckpoint (contents.ts:513:13)
    at async index.ts:120:15
    at async _.createCheckpoint (index.ts:1308:11)
D @ dialog.tsx:43
_handleError @ context.ts:769
(anonymous) @ context.ts:714
Promise.catch (async)
_revert @ context.ts:711
initialize @ context.ts:269
await in initialize (async)
(anonymous) @ manager.ts:590
Promise.then (async)
_createOrOpenDocument @ manager.ts:590
open @ manager.ts:365
openOrReveal @ manager.ts:401
handleOpen @ listing.ts:1021
evtDblClick @ listing.ts:1116
handleEvent @ listing.ts:666
manager.ts:605 Failed to initialize the context with 'notebook' for rocket%20equations.ipynb Error: Could not find file with path rocket%20equations.ipynb
    at m.createCheckpoint (contents.ts:513:13)
    at async index.ts:120:15
    at async _.createCheckpoint (index.ts:1308:11)
(anonymous) @ manager.ts:605
Promise.catch (async)
_createOrOpenDocument @ manager.ts:604
open @ manager.ts:365
openOrReveal @ manager.ts:401
handleOpen @ listing.ts:1021
evtDblClick @ listing.ts:1116
handleEvent @ listing.ts:666
index.ts:467 TypeError: Cannot set properties of undefined (setting 'text')
    at m._setValue (jsoneditor.ts:331:19)
    at set source [as source] (jsoneditor.ts:134:10)
    at e.NotebookMetadataEditorTool._update (notebooktools.ts:637:19)
    at e.NotebookMetadataEditorTool.onActiveNotebookPanelChanged (notebooktools.ts:623:12)
    at e.NotebookMetadataEditorTool.processMessage (notebooktools.ts:345:16)
    at c (index.ts:530:15)
    at Object.e [as sendMessage] (index.ts:220:7)
    at notebooktools.ts:172:7
    at f (iter.ts:227:9)
    at P._onActiveNotebookPanelChanged (notebooktools.ts:171:5)</pre>
</details>

**Comment by jtpio** [comment]
Thanks @tomjakubowski for reporting the issue :+1: 

Since "File -> Open from URL" comes from JupyterLab, do you know if this issue also occurs in normal JupyterLab? If yes then we should fix it there.

**Comment by tomjakubowski** [comment]
I'm able to import the notebook in Jupyterlab. 

<img width="1392" alt="Screenshot 2023-10-16 at 4 24 07 PM" src="https://github.com/jupyterlite/jupyterlite/assets/667901/d4d25eb8-7979-407e-97a0-47b70df6c051">

It could be something in JupyterLiteServer - maybe somewhere along the line something is being double-encoded or is not being decoded.

**Comment by jtpio** [comment]
Thanks for checking :+1: 

> It could be something in JupyterLiteServer - maybe somewhere along the line something is being double-encoded or is not being decoded.

Yes very likely, iirc the "Open from URL" command uses the contents API to upload the file to the server.

**Comment by jtpio** [comment]
@tomjakubowski just checking if this is still an issue with the latest JupyterLite 0.6.0?

Testing with:

- https://jupyterlite.readthedocs.io/en/stable/_static/lab/index.html
- https://raw.githubusercontent.com/mds2/rocketry/main/rocket%20equations.ipynb

Appears to be working fine now?

https://github.com/user-attachments/assets/dd87cd7d-a515-4345-a7cb-4421ba1d7078

This may have been fixed by https://github.com/jupyterlite/jupyterlite/pull/1590, which dropped the "server" part of JupyterLite and moved the contents management to a drive.
