### ISSUE TITLE
Click the "Restart the Kernel and Run All Cells" button, error occurs about 50% of the time.(Success and error occur alternately)

### ISSUE THREAD

**Issue by tanaga9** [jupyterlite/jupyterlite#1237]
## Description

When click the "Restart the Kernel and Run All Cells" button, the following error occurs about 50% of the time.
If you repeat something multiple times, success and error will occur alternately.

```
index.es6.js:308 TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
    at te.items (model.js:183:21)
    at te.items (model.js:563:28)
    at te.items (model.js:601:29)
    at J._onModelRefreshed (listing.js:1686:40)
    at d (index.es6.js:555:18)
    at e.emit (index.es6.js:513:17)
    at s.emit (index.es6.js:112:17)
    at te.onRunningChanged (model.js:513:25)
    at d (index.es6.js:555:18)
    at e.emit (index.es6.js:513:17)
```

The process that should have continued stops. (Kernel down ?)

## Reproduce

1. Write a simple notebook (that does not raise an exception).
2. Click on "Restart the Kernel and Run All Cells" button
3. Restart
4. Repeat 2 and 3.

## Context

- JupyterLite version: 0.2.0
- Operating System and version: Google Chrome 118.0.5993.117 (Official Build) (x86_64)
- Browser and version:masOS Sonoma 14.0

**Comment by tanaga9** [comment]
I tried it on my iPad, and it occurs at about 30%, not 50%.

**Comment by jtpio** [comment]
Thanks @tanaga9 for reporting.

Out of curiosity does this happen with stock JupyterLab 4 as well?

Otherwise it can indeed be an issue with JupyterLite only, and could also be related to the fact that kernels take a bit more time to start.

**Comment by tanaga9** [comment]
Hi @jtpio 
I have been using this button in JupyterLab 4.0.5 for a while now, and I have never seen this happen.
