### ISSUE TITLE
Creating a "flat" distribution

### ISSUE THREAD

**Issue by psychemedia** [jupyterlite/jupyterlite#1242]
Building a Jupyterlite site seems to create a structure:

```text
./
./index.html
./lab/index.html
./repl/index.html etc
```

I am trying to get a Jupyterlite running inside a Moodle VLE, which allows me to import a .zip file with an index.html at the root that can be served via an iframe.

With a default Jupyerlite build, the page just hangs with an error:

```text
Uncaught TypeError: Cannot read properties of null (reading 'href')
    at main (config-utils.js:259:26)
    at async config-utils.js:267:1
```

This is an error on `bundle.src = preloader.href;` arising from `document.getElementById(LITE_MAIN)` not found (which is to say, an element with id `'jupyter-lite-main'`.

If I manually hack the iframe URL in browser dev tools away from `long_path/index.html` to point to `long_path/lab/index.html` then I can see JupyterLab, or hack it to `long_path/repl/index.html` and the repl loads.

<img width="919" alt="image" src="https://github.com/jupyterlite/jupyterlite/assets/82988/25f3a2ac-9a7e-4951-8543-42e8a0a61634">

So is there a way I can build a simple "flat" distribution with just lab, or just the repl, where the lab (or repl) index page is at the top level? Also, how would I install kernels into it?

**Comment by jtpio** [comment]
Currently the file structure is outlined in the top-level `index.html`, and assumes the available apps are placed in their own subfolders:

https://github.com/jupyterlite/jupyterlite/blob/bde12e5209c37e278c5b84af9ebe40fc17696475/app/index.html#L17

There is also some logic in `config-utils.js` to recursively look up and merge configuration: https://github.com/jupyterlite/jupyterlite/blob/main/app/config-utils.js

It might be possible to create a `jupyter-lite.json` file with the right configuration to produce a flat distribution, but not entirely sure.

**Comment by psychemedia** [comment]
Thanks... I've also been having an issue with JupytetLite hanging if it is down a path, eg on GitHub pages ( https://github.com/jupyterlite/jupyterlite/issues/1243#issuecomment-1809098302 )
