### ISSUE TITLE
Fatal TypeError in mi.readdir: e.push is not a function

### ISSUE THREAD

**Issue by NeilStrickland** [jupyterlite/jupyterlite#1243]
## Description

While trying to use Jupyter Lite with Pyodide, I see a fatal error in the Chrome Dev Console, with a message asking me to report it to the Pyodide maintainers.  I raised an issue on the Pyodide tracker (https://github.com/pyodide/pyodide/issues/4278) but it was suggested there that the problem is actually in code specific to Jupyter Lite.  (I have not understood the code well enough to judge that myself.)

## Reproduce

The file https://strickland1.org/courses/MAS2008/lectures/l.html generates the error consistently. It has three Jupyter Lite notebooks in iframes, with URLs as follows:

https://neilstrickland.github.io/jlite/lab?path=lecture01/arithmetic.ipynb
https://neilstrickland.github.io/jlite/lab?path=lecture01/data_types.ipynb
https://neilstrickland.github.io/jlite/lab?path=lecture01/equals.ipynb
If I open these URLs individually, I sometimes get the same error, and sometimes not.

## Expected behavior

When I press SHIFT-ENTER on the first cell in a Jupyter Lite notebook, I expect that the cell will be evaluated and the result will be shown below the cell after a brief pause, during which the cell number will change from [ ]: to [ * ]:. In cases where the error occurs, the cell number changes to [ * ]: and does not change back, no output is shown, and error messages appear in the Chrome Dev Console.

## Context

- JupyterLite version: 0.1.3
- Operating System and version: Windows 11
- Browser and version: Chrome Version 118.0.5993.118 (Official Build) (64-bit)

<details><summary>Browser Output</summary>
<pre>
Uncaught TypeError: e.push is not a function
    at mi.readdir (worker.js:7:3746)
    at hi.readdir (worker.js:7:2754)
    at Object.readdir (pyodide.asm.js:9:213065)
    at ___syscall_getdents64 (pyodide.asm.js:9:257635)
    at pyodide.asm.wasm:0x444e17
    at pyodide.asm.wasm:0x38660e
    at pyodide.asm.wasm:0x269016
    at pyodide.asm.wasm:0x260a7b
    at pyodide.asm.wasm:0x25e033
    at pyodide.asm.wasm:0x1e3f77
</pre>
</details>
A full log is here:
[strickland1.org-1698880948135.log](https://github.com/jupyterlite/jupyterlite/files/13248468/strickland1.org-1698880948135.log)

**Comment by andeplane** [comment]
Ok! When I open https://strickland1.org/courses/MAS2008/lectures/l.html I can execute all cells on all the pages you have there. Not saying you aren't experiencing it, but I can't reproduce it on my machine now.

**Comment by NeilStrickland** [comment]
I am still having problems on several different machines.  Sometimes it works with the file  https://strickland1.org/courses/MAS2008/lectures/l.html (which contains three iframed notebooks) but not with 
https://strickland1.org/courses/MAS2008/lectures/lecture01.html (which contains 11).

**Comment by tgourdel** [comment]
I have occasionally encountered similar error messages but have not been able to reproduce them consistently (was using Jupyterlite and pyodide kernel 0.1.3).

Additionally, I'm also seeing the error on your page:
![image](https://github.com/jupyterlite/jupyterlite/assets/15718239/22128f1b-3ccf-44ec-bee1-78acdaa6d266)

As you can see, it worked fine initially; I was able to execute a few cells. I think the issues started when I switched to others, or after refreshing, it's hard to tell. I have not found a reproducible sequence that consistently leads to the error, which makes diagnosing difficult.

@NeilStrickland have you tried to clear all your browser cache for example?

**Comment by NeilStrickland** [comment]
I have now tried this in Microsoft Edge, where I am willing to delete absolutely all settings, site data, cookies and so on.  I cleared everything then visited https://strickland1.org/courses/MAS2008/lectures/lecture01.html.  I successfully executed all the cells in the first three notebooks.  However, the remaining notebooks would not load at all, I just got the "Keep Waiting/Clear Workspace" screen, and nothing happened when I clicked either option.  I then reloaded the page, without clearing all data again.  At that point I got the message "e.push is not a function" again.

**Comment by psychemedia** [comment]
I am getting the same error, in ways I can't reliably reproduce, in Chrome on various recently built sites, using latest (unpinned) PyPi releases and pyodide kernel. 

```text
jupyterlite-core
jupyterlab
notebook

# Python kernels (optional)
jupyterlite-pyodide-kernel

# Python: ipywidget library for Jupyter notebooks (optional)
ipywidgets>=8.1.1,<9
# Python: ipyevents library for Jupyter notebooks (optional)
ipyevents>=2.0.1
# Python: interative Matplotlib library for Jupyter notebooks (optional)
ipympl>=0.8.2
```

I was also wondering about how stable things are if both lab and notebook are open at the same time?

**Comment by psychemedia** [comment]
Poking around one of my set-ups, I was building a GH Pages site with a Jupyter Book at `/` and JupyterLite in `/jupyterlite`. That was behaving really badly... Keeping JupyterLite in `/jupyterlite` and moving book to `/book` and leaving the root empty was much happier. Putting a blank `index.html` into `/`  (via `touch index.html`) broke things again. So it seems the JuupyterLite is happy in a path if there is no index file in `/`?

**Comment by dwootton** [comment]
Experienced the same issue. Clearing Local storage, session storage, and index DB via the devtools application tab seemed to resolve it for me. I encountered it running off of [the jupyterlite docs site.](https://jupyterlite.readthedocs.io/en/stable/_static/lab/index.html).

**Comment by martenrichter** [comment]
I also ran into this issue. I had two tabs open, one with lab the other with notebooks. I looked into the debugger, and it looks like, that instead of getting the directory content the function returned and object with file attributes. It looks for me like the ordering of requests and response where shuffled. So either the two tabs are interfering each other or in the asynchronous api at some point the request and response order is changed.
