### ISSUE TITLE
Menu "Save and export notebook as" not showing up

### ISSUE THREAD

**Issue by Popcorn7020** [jupyterlite/jupyterlite#1364]
## Description

In the online version of jupiter lab (JupyterLite) I'm unable to use the "Save and export notebook as", no menu is showing up
![image](https://github.com/jupyterlite/jupyterlite/assets/155472414/2419eac4-ec4d-4ff8-8889-647fb7d49293)

## Reproduce

1. Go to https://jupyter.org/try-jupyter/lab/
2. Select File menu
3. Select "Save and export notebook as" menu

## Expected behavior

I expect that a menu shows up to allow exporting and downloading the notebooks

## Context

- Browser and version: Edge 123.0.2420.65 and Chrome 123.0.6312.86

**Comment by jtpio** [comment]
Thanks @Popcorn7020.

This looks like a duplicate of https://github.com/jupyterlite/jupyterlite/issues/543. Should we close it and continue the discussion in https://github.com/jupyterlite/jupyterlite/issues/543?

**Comment by WesErg** [comment]
This is not a duplicate of #543.  I am suffering the same problem.  Is there any solution to this?

**Comment by horasjey** [comment]
i'm having this problem, 
anoyone have solusi..?

**Comment by vmoreno14** [comment]
Did anyone find a solution

**Comment by stientist** [comment]
Hi everyone, this worked for me: After making your notebook, just go to https://jupyter.org/try-jupyter/tree/, which is basically like "file explorer" for your online jup nb's. Navigate to "notebooks" and just download! Pls let me know if this worked for you!  

Assuming that my solution actually works for everyone else,  I think that jupyter's IT did not respond because it seems like it would be easy for us to troubleshoot if we put in some effort. However, I figured this out by accident, and I have no idea how I even got to the tree from my initial notebook. Although I agree it was a straightforward solution, clearly there are many confused but competent users.

**Comment by nicae-dev** [comment]
it's not working for me... We've installed jupyter on local server. In chrome console there is a 500 error in JS:
`[jupyter-domain]/user/username/api/nbconvert?1731677498679 500 (Internal Server Error)`

and if i try to run nbconvert in Ubuntu console, it ends up with strange error:

` jupyter nbconvert --to pdf test_simple.ipynb`

```
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbconvert", line 5, in <module>
    from nbconvert.nbconvertapp import main
  File "/usr/local/lib/python3.8/dist-packages/nbconvert/nbconvertapp.py", line 193, in <module>
    class NbConvertApp(JupyterApp):
  File "/usr/local/lib/python3.8/dist-packages/nbconvert/nbconvertapp.py", line 252, in NbConvertApp
    Options include {get_export_names()}.
  File "/usr/local/lib/python3.8/dist-packages/nbconvert/exporters/base.py", line 145, in get_export_names
    e = get_exporter(exporter_name)(config=config)
  File "/usr/local/lib/python3.8/dist-packages/nbconvert/exporters/base.py", line 106, in get_exporter
    exporter = items[0].load()
  File "/usr/local/lib/python3.8/dist-packages/importlib_metadata/__init__.py", line 189, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.8/dist-packages/jupyter_contrib_nbextensions/nbconvert_support/__init__.py", line 5, in <module>
    from .collapsible_headings import ExporterCollapsibleHeadings
  File "/usr/local/lib/python3.8/dist-packages/jupyter_contrib_nbextensions/nbconvert_support/collapsible_headings.py", line 6, in <module>
    from notebook.services.config import ConfigManager
ModuleNotFoundError: No module named 'notebook.services'
```

**Comment by Akeeda** [comment]
I followed the steps from the below link, and it solved the problem.

https://www.devgem.io/posts/troubleshooting-jupyter-notebook-save-and-export-issues-after-upgrade

**Comment by randreassen89** [comment]
> I followed the steps from the below link, and it solved the problem.
> 
> https://www.devgem.io/posts/troubleshooting-jupyter-notebook-save-and-export-issues-after-upgrade

This link does not work.... I am suffering the same problem.

**Comment by beniroquai** [comment]
same here. Jupyter lite with Pyodide.

**Comment by Pat4fix** [comment]
same cant export

**Comment by raquemustang** [comment]
> Hi everyone, this worked for me: After making your notebook, just go to https://jupyter.org/try-jupyter/tree/, which is basically like "file explorer" for your online jup nb's. Navigate to "notebooks" and just download! Pls let me know if this worked for you!
> 
> Assuming that my solution actually works for everyone else, I think that jupyter's IT did not respond because it seems like it would be easy for us to troubleshoot if we put in some effort. However, I figured this out by accident, and I have no idea how I even got to the tree from my initial notebook. Although I agree it was a straightforward solution, clearly there are many confused but competent users.

it workedd~ thanks mate!

**Comment by RMattB1** [comment]
https://jupyter.org/try-jupyter/tree/notebooks
is not a solution for local installations of jupyterlite.

**Comment by aiAintEasy-HolyCalamity** [comment]
still an issue

**Comment by hgustafsson** [comment]
As a first step it would be useful to be able to export as HTML if PDF export is too complicated in the client browser.
