### ISSUE TITLE
Can JupyterLite / Lab interfere with other JupyterLab installs?

### ISSUE THREAD

**Issue by psychemedia** [jupyterlite/jupyterlite#1370]
I've been running various combinations of JupyterLab server, (local Pyhton Lab server, JupyterLite servers on localhost) and I was wondering if the JupyterLite environment could somehow break other JupyterLab environments.

Trying to run Jupyter Lab (as `jupyter lab`), the UI launches but I get an issue trying to open a notebook:

<img width="400" alt="image" src="https://github.com/jupyterlite/jupyterlite/assets/82988/c201326d-8f41-49c4-bf2d-c8041debeb51">

I can connect to a JupyterLab terminal launched for the same base kernel and it runs fine (so the kernel is there, works correctly, etc).

Checking terminal messages, I note the rather odd:

```text
Error: Shared module @jupyterlite/server doesn't exist in shared scope default
    at u (consumes:19:57)
    at consumes:104:2
    at consumes:85:9
    at 144 (consumes:139:14)
    at consumes:180:42
    at Array.forEach (<anonymous>)
    at P.f.consumes (consumes:163:25)
    at ensure chunk:6:25
    at Array.reduce (<anonymous>)
    at P.e (ensure chunk:5:56)

Error: Shared module @jupyterlite/server doesn't exist in shared scope default
    at i (remoteEntry.ff7ee85ad1087146a275.js:1:4787)
    at remoteEntry.ff7ee85ad1087146a275.js:1:5456
    at remoteEntry.ff7ee85ad1087146a275.js:1:5423
    at 594 (remoteEntry.ff7ee85ad1087146a275.js:1:5750)
    at remoteEntry.ff7ee85ad1087146a275.js:1:6247
    at Array.forEach (<anonymous>)
    at j.f.consumes (remoteEntry.ff7ee85ad1087146a275.js:1:6077)
    at remoteEntry.ff7ee85ad1087146a275.js:1:995
    at Array.reduce (<anonymous>)
    at j.e (remoteEntry.ff7ee85ad1087146a275.js:1:973)

```

Trying to open the notebook I get:

```text

TypeError: Cannot read properties of undefined (reading 'connect')
    at g.createNew (496.c4b5fd0cdd5526f0f009.js?v=c4b5fd0cdd5526f0f009:1:3571)
    at w._initializeWidget (widgetmanager.js:102:41)
    at w.createWidget (widgetmanager.js:88:14)
    at j._createOrOpenDocument (manager.js:561:44)
    at j.open (manager.js:374:21)
    at j.openOrReveal (manager.js:401:21)
    at index.js:511:40
    at async R (index.js:1330:19)=

```

On the server, the notebooks are being opened and the kernel started, so it's definitely a front end issue?

**Comment by psychemedia** [comment]
issue was nothing do elaborate, though I wonder at the jupyterlite reference. A dev env issue following a machine restart and building / tresting across  different  environments
