### ISSUE TITLE
notebook execution fails on firefox when notebook is in a subfolder and jupyterlite is in an iframe

### ISSUE THREAD

**Issue by magland** [jupyterlite/jupyterlite#1399]
## Description

I am running into an error under the following conditions

* In a Firefox browser
* JupyterLite Notebook is in a subfolder
* JupyterLite is embedded in an iframe

With these conditions, notebook cells do not execute and I get the following in the console

```
  Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python311.zip/_pyodide/_base.py", line 573, in eval_code_async
    await CodeRunner(
  File "/lib/python311.zip/_pyodide/_base.py", line 395, in run_async
    await coroutine
  File "exec", line 9, in module
OSError: [Errno 28] Invalid argument: 'folder1'
```

Here folder1 is the name of the folder I created. It contains the notebook.

This problem does not occur if (a) the notebook is at the root directory; or (b) using Chrome; or (c) JupyterLite is not embedded in an iframe.

## Reproduce

I have created this jsfiddle. Open it in firefox and follow the instructions on the page

https://jsfiddle.net/euvnxy1j/2/

Here's the code for the fiddle:

```html
<body>
<div style="max-width:800px">
  <p>
  JupyterLite is embedded in the iframe below. Try creating a new notebook and executing a trivial cell, e.g. `1+1`. It should work on both Chrome and Firefox. Now try creating a folder named folder1 and create a new notebook inside that folder. Try executing a cell there. In Chrome it works. In Firefox it doesn't work, and you get the the error message printed at the bottom of this page.
  </p>
</div>

<div>
  <iframe width=800 height=800 src="https://jupyter.org/try-jupyter/lab/index.html"></iframe>
</div>

<div>
  <p>
  Error message from Firefox when trying to execute a notebook cell in a notebook that is saved in a subfolder when JupyterLite is embedded in an iframe:
  </p>
  <pre>
  Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python311.zip/_pyodide/_base.py", line 573, in eval_code_async
    await CodeRunner(
  File "/lib/python311.zip/_pyodide/_base.py", line 395, in run_async
    await coroutine
  File "exec", line 9, in module
OSError: [Errno 28] Invalid argument: 'folder1'
  </pre>
</div>

</body>
```

**Comment by magland** [comment]
Following up, I found a related problem that may shed some light.

Go to that same jsfiddle, open a pyodide notebook, and try executing the following:

```python
with open('test.txt', 'w') as f:
    f.write('test content')
```

On chrome it works fine, but again on firefox (only when in an iframe) I get the following error

```bash
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Cell In[1], line 1
----> 1 with open('test.txt', 'w') as f:
      2     f.write('test content')

File /lib/python3.11/site-packages/IPython/core/interactiveshell.py:324, in _modified_open(file, *args, **kwargs)
    317 if file in {0, 1, 2}:
    318     raise ValueError(
    319         f"IPython won't let you open fd={file} by default "
    320         "as it is likely to crash IPython. If you know what you are doing, "
    321         "you can use builtins' open."
    322     )
--> 324 return io_open(file, *args, **kwargs)

OSError: [Errno 28] Invalid argument: 'test.txt'
```

So it's evidently having trouble with the internal file system... but strangely only on firefox when it is embedded in an iframe.

**Comment by martinRenou** [comment]
It's possible that in this case the communication with the service worker is not working.

We're looking into making things less flaky by getting rid of the service worker for filesystem APIs: 
- https://github.com/jupyterlite/xeus/pull/87
- https://github.com/jupyterlite/jupyterlite/pull/1383
This work will depend on `Atomics.wait` and `SharedArrayBuffer` instead of the service worker, it has the downside of being [disabled by default on browsers](https://blog.mozilla.org/security/2018/01/03/mitigations-landing-new-class-timing-attack) and hidden behind a flag. No perfect solution.

**Comment by magland** [comment]
Thanks for the reply @martinRenou 

I think for now I'll disable the kernel and let this be a readonly view. But I'd love to disable the popup for "select a kernel"

I  [read](https://discourse.jupyter.org/t/open-notebooks-with-no-kernel-without-select-kernel-popup/25226) that the way to do that is

```python
c.LabServerApp.notebook_starts_kernel = False
```

in `.jupyter/jupyter_lab_config.py`

But I don't know how to specify that when building the site. Would that go somewhere in `jupyter-lite.json`?

(Let me know if I shoud start a new thread for this)

**Comment by magland** [comment]
I need to be able to configure extensions and have the full jupyterlab environment (edit peripheral .py files etc). Also need to be able to edit files (even without kernel)

**Comment by martinRenou** [comment]
I see. I don't know about your question concerning the `LabServerApp` config, this config is really a server config and we don't have a jupyter server running when it comes to jupyterlite. But probably jupyterlite has an equivalent for this config entry? 

cc. @jtpio

**Comment by jtpio** [comment]
Right, it sounds like this information would be passed down to the frontend as a page config option, need to double check. If so, it would indeed be configurable via a `jupyter-lite.json`.

**Comment by jtpio** [comment]
Looks like such option is read from the page config here: https://github.com/jupyterlab/jupyterlab/blob/21ffea9749637633b4a4d82b3f277b55f80afb3d/packages/notebook-extension/src/index.ts#L1189

@magland would you be able to try the following configuration in a `jupyter-lite.json` file?

```json
{
  "jupyter-lite-schema-version": 0,
  "jupyter-config-data": {
    "notebookStartsKernel": true
  }
}
```

**Comment by magland** [comment]
That worked, thanks so much!

In case you folks are interested, here's my project
https://github.com/magland/jpfiddle

Allows frictionless sharing of notebooks and directories using an embedded jupyterlite or a locally running jupyterlab.

**Comment by jtpio** [comment]
@magland about the original issue, it was very likely an issue with Firefox, similar to https://github.com/jupyterlite/jupyterlite/issues/1341#issuecomment-2836425417, which was recently fixed.

Would you be able to check again if accessing files works as expected?

**Comment by jtpio** [comment]
Closing as this appears to have been fixed in Firefox.
