### ISSUE TITLE
Pyodide crashes when starting two pyodide kernels at the same time in Chrome

### ISSUE THREAD

**Issue by krassowski** [jupyterlite/jupyterlite#1460]
## Description

Starting two pyodide kernels at the same time in JupyterLab or embedding two pyodide REPLs with `code=...` in one page via iframes causes both of them to crash with:

```js
pyodide.asm.js:10 Pyodide has suffered a fatal error. Please report this to the Pyodide maintainers.
API.fatal_error @ pyodide.asm.js:10
API.maybe_fatal_error @ pyodide.asm.js:10
callPyObjectKwargs @ pyodide.asm.js:10
Module.callPyObjectMaybePromising @ pyodide.asm.js:10
wrapper @ pyodide.asm.js:10
Kn.e.port1.onmessage @ pyodide.asm.js:10
pyodide.asm.js:10 The cause of the fatal error was:
API.fatal_error @ pyodide.asm.js:10
API.maybe_fatal_error @ pyodide.asm.js:10
callPyObjectKwargs @ pyodide.asm.js:10
Module.callPyObjectMaybePromising @ pyodide.asm.js:10
wrapper @ pyodide.asm.js:10
Kn.e.port1.onmessage @ pyodide.asm.js:10
pyodide.asm.js:10 TypeError: Cannot read properties of undefined (reading 'getTime')
    at Object.doStat (pyodide.asm.js:10:233214)
    at ___syscall_stat64 (pyodide.asm.js:10:274177)
    at pyodide.asm.wasm:0x49711e
    at pyodide.asm.wasm:0x4b0d76
    at pyodide.asm.wasm:0x3dcd2f
    at pyodide.asm.wasm:0x3dc5f5
    at pyodide.asm.wasm:0x29f1bc
    at pyodide.asm.wasm:0x2a4cf1
    at pyodide.asm.wasm:0x1c3806
    at pyodide.asm.wasm:0x1c4570
```

This is in an environment with numpy, sklearn, pandas and matplotlib installed (after these get loaded), see details below in `Browser Output`

## Reproduce

1. Create a static page with two iframes
2. Visit it in Chrome
3. Wait and see error one every second load (this does not happen every time but often does)
4. Remove the second iframe
5. Visit the page again
6. See no error

Note: it works fine in Firefox - have not seen it error out once.

Looks like a Chrome specific concurrency issue when multiple instances of pyodide are on the page. It's surprising as this also happens if these are in iframes but I guess it is using the same service worker?

## Expected behavior

No crash, or documentation that this is not supported

## Context

- JupyterLite version: 0.4.0
- Operating System and version: Ubuntu 24.04
- Browser and version: Chrome 127.0.6533.99 (Official Build) (64-bit)

<details><summary>Browser Output</summary>
<pre>
JupyterLite ServiceWorker was already registered
index.js:192 Kernel filesystem and JupyterLite contents will be synced
serverconnection.js:220 
        
        
       GET https://xxx.github.io/jupyterlite-demo/server-proxy/servers-info?1723752674676 404 (Not Found)
e.handleRequest @ serverconnection.js:220
e.makeRequest @ serverconnection.js:65
activate @ 388.a55ea4aace02879f4e8f.js?v=a55ea4aace02879f4e8f:1
(anonymous) @ index.es6.js:1851
Promise.then
activatePlugin @ index.es6.js:1851
(anonymous) @ index.es6.js:2015
start @ index.es6.js:2014
P @ index.js:451
await in P
(anonymous) @ bootstrap.js:91
await in (anonymous)
69610 @ bootstrap.js:65
w @ bootstrap:19
(anonymous) @ startup:4
w.O @ chunk loaded:23
(anonymous) @ startup:5
(anonymous) @ bundle.js?_=1c7ca05:1
388.a55ea4aace02879f4e8f.js?v=a55ea4aace02879f4e8f:1 Server proxy info not available
activate @ 388.a55ea4aace02879f4e8f.js?v=a55ea4aace02879f4e8f:1
await in activate
(anonymous) @ index.es6.js:1851
Promise.then
activatePlugin @ index.es6.js:1851
(anonymous) @ index.es6.js:2015
start @ index.es6.js:2014
P @ index.js:451
await in P
(anonymous) @ bootstrap.js:91
await in (anonymous)
69610 @ bootstrap.js:65
w @ bootstrap:19
(anonymous) @ startup:4
w.O @ chunk loaded:23
(anonymous) @ startup:5
(anonymous) @ bundle.js?_=1c7ca05:1
service-manager.js:66 JupyterLite ServiceWorker was already registered
index.js:192 Kernel filesystem and JupyterLite contents will be synced
serverconnection.js:220 
        
        
       GET https://xxx.github.io/jupyterlite-demo/server-proxy/servers-info?1723752675117 404 (Not Found)
e.handleRequest @ serverconnection.js:220
e.makeRequest @ serverconnection.js:65
activate @ 388.a55ea4aace02879f4e8f.js?v=a55ea4aace02879f4e8f:1
(anonymous) @ index.es6.js:1851
Promise.then
activatePlugin @ index.es6.js:1851
(anonymous) @ index.es6.js:2015
start @ index.es6.js:2014
P @ index.js:451
await in P
(anonymous) @ bootstrap.js:91
await in (anonymous)
69610 @ bootstrap.js:65
w @ bootstrap:19
(anonymous) @ startup:4
w.O @ chunk loaded:23
(anonymous) @ startup:5
(anonymous) @ bundle.js?_=1c7ca05:1
388.a55ea4aace02879f4e8f.js?v=a55ea4aace02879f4e8f:1 Server proxy info not available
activate @ 388.a55ea4aace02879f4e8f.js?v=a55ea4aace02879f4e8f:1
await in activate
(anonymous) @ index.es6.js:1851
Promise.then
activatePlugin @ index.es6.js:1851
(anonymous) @ index.es6.js:2015
start @ index.es6.js:2014
P @ index.js:451
await in P
(anonymous) @ bootstrap.js:91
await in (anonymous)
69610 @ bootstrap.js:65
w @ bootstrap:19
(anonymous) @ startup:4
w.O @ chunk loaded:23
(anonymous) @ startup:5
(anonymous) @ bundle.js?_=1c7ca05:1
index.js:60 Pyodide contents will be synced with Jupyter Contents
index.js:60 Pyodide contents will be synced with Jupyter Contents
327.68dbf8491690b3aff1e7.js?v=68dbf8491690b3aff1e7:1 Failed to fetch ipywidgets through the "jupyter.widget.control" comm channel, fallback to fetching individual model state. Reason: Control comm did not respond in time
_loadFromKernel @ 327.68dbf8491690b3aff1e7.js?v=68dbf8491690b3aff1e7:1
await in _loadFromKernel
_loadFromKernel @ 446.fdf8b1b233cb8c1783f6.js?v=fdf8b1b233cb8c1783f6:1
restoreWidgets @ 446.fdf8b1b233cb8c1783f6.js?v=fdf8b1b233cb8c1783f6:1
T @ 446.fdf8b1b233cb8c1783f6.js?v=fdf8b1b233cb8c1783f6:1
(anonymous) @ 446.fdf8b1b233cb8c1783f6.js?v=fdf8b1b233cb8c1783f6:1
ne @ 446.fdf8b1b233cb8c1783f6.js?v=fdf8b1b233cb8c1783f6:1
await in ne
re @ 446.fdf8b1b233cb8c1783f6.js?v=fdf8b1b233cb8c1783f6:1
(anonymous) @ 446.fdf8b1b233cb8c1783f6.js?v=fdf8b1b233cb8c1783f6:1
c @ index.es6.js:555
e.emit @ index.es6.js:513
emit @ index.es6.js:112
(anonymous) @ widgettracker.js:39
c @ index.es6.js:555
e.emit @ index.es6.js:513
emit @ index.es6.js:112
add @ restorablepool.js:132
add @ widgettracker.js:120
I @ index.js:257
await in I
execute @ index.js:375
execute @ index.es6.js:365
(anonymous) @ index.js:111
Promise.then
activate @ index.js:110
(anonymous) @ index.es6.js:1851
327.68dbf8491690b3aff1e7.js?v=68dbf8491690b3aff1e7:1 Failed to fetch ipywidgets through the "jupyter.widget.control" comm channel, fallback to fetching individual model state. Reason: Control comm did not respond in time
_loadFromKernel @ 327.68dbf8491690b3aff1e7.js?v=68dbf8491690b3aff1e7:1
await in _loadFromKernel
_loadFromKernel @ 446.fdf8b1b233cb8c1783f6.js?v=fdf8b1b233cb8c1783f6:1
restoreWidgets @ 446.fdf8b1b233cb8c1783f6.js?v=fdf8b1b233cb8c1783f6:1
T @ 446.fdf8b1b233cb8c1783f6.js?v=fdf8b1b233cb8c1783f6:1
(anonymous) @ 446.fdf8b1b233cb8c1783f6.js?v=fdf8b1b233cb8c1783f6:1
ne @ 446.fdf8b1b233cb8c1783f6.js?v=fdf8b1b233cb8c1783f6:1
await in ne
re @ 446.fdf8b1b233cb8c1783f6.js?v=fdf8b1b233cb8c1783f6:1
(anonymous) @ 446.fdf8b1b233cb8c1783f6.js?v=fdf8b1b233cb8c1783f6:1
c @ index.es6.js:555
e.emit @ index.es6.js:513
emit @ index.es6.js:112
(anonymous) @ widgettracker.js:39
c @ index.es6.js:555
e.emit @ index.es6.js:513
emit @ index.es6.js:112
add @ restorablepool.js:132
add @ widgettracker.js:120
I @ index.js:257
await in I
execute @ index.js:375
execute @ index.es6.js:365
(anonymous) @ index.js:111
Promise.then
activate @ index.js:110
(anonymous) @ index.es6.js:1851
pyodide.asm.js:10 Loading micropip, packaging
pyodide.asm.js:10 Loaded micropip, packaging
pyodide.asm.js:10 Loading micropip, packaging
pyodide.asm.js:10 Loaded micropip, packaging
pyodide.asm.js:10 Loading openssl, ssl
pyodide.asm.js:10 Loading openssl, ssl
pyodide.asm.js:10 Loaded openssl, ssl
pyodide.asm.js:10 Loaded openssl, ssl
pyodide.asm.js:10 Loading sqlite3
pyodide.asm.js:10 Loaded sqlite3
pyodide.asm.js:10 Loading sqlite3
pyodide.asm.js:10 Loaded sqlite3
pyodide.asm.js:10 Loading traitlets
pyodide.asm.js:10 Loaded traitlets
pyodide.asm.js:10 Loading traitlets
pyodide.asm.js:10 Loaded traitlets
pyodide.asm.js:10 traitlets already loaded from default channel
pyodide.asm.js:10 sqlite3 already loaded from default channel
pyodide.asm.js:10 Loading Pygments, asttokens, decorator, executing, ipython, matplotlib-inline, prompt_toolkit, pure_eval, six, stack_data, wcwidth
pyodide.asm.js:10 traitlets already loaded from default channel
pyodide.asm.js:10 sqlite3 already loaded from default channel
pyodide.asm.js:10 Loading Pygments, asttokens, decorator, executing, ipython, matplotlib-inline, prompt_toolkit, pure_eval, six, stack_data, wcwidth
pyodide.asm.js:10 Loaded Pygments, asttokens, decorator, executing, ipython, matplotlib-inline, prompt_toolkit, pure_eval, six, stack_data, wcwidth
pyodide.asm.js:10 Loaded Pygments, asttokens, decorator, executing, ipython, matplotlib-inline, prompt_toolkit, pure_eval, six, stack_data, wcwidth
pyodide.asm.js:10 Loading joblib, numpy, openblas, scikit-learn, scipy, threadpoolctl
pyodide.asm.js:10 Loading joblib, numpy, openblas, scikit-learn, scipy, threadpoolctl
pyodide.asm.js:10 Loaded joblib, numpy, openblas, scikit-learn, scipy, threadpoolctl
pyodide.asm.js:10 Pyodide has suffered a fatal error. Please report this to the Pyodide maintainers.
API.fatal_error @ pyodide.asm.js:10
API.maybe_fatal_error @ pyodide.asm.js:10
callPyObjectKwargs @ pyodide.asm.js:10
Module.callPyObjectMaybePromising @ pyodide.asm.js:10
wrapper @ pyodide.asm.js:10
Kn.e.port1.onmessage @ pyodide.asm.js:10
pyodide.asm.js:10 The cause of the fatal error was:
API.fatal_error @ pyodide.asm.js:10
API.maybe_fatal_error @ pyodide.asm.js:10
callPyObjectKwargs @ pyodide.asm.js:10
Module.callPyObjectMaybePromising @ pyodide.asm.js:10
wrapper @ pyodide.asm.js:10
Kn.e.port1.onmessage @ pyodide.asm.js:10
pyodide.asm.js:10 TypeError: Cannot read properties of undefined (reading 'getTime')
    at Object.doStat (pyodide.asm.js:10:233214)
    at ___syscall_stat64 (pyodide.asm.js:10:274177)
    at pyodide.asm.wasm:0x49711e
    at pyodide.asm.wasm:0x4b0d76
    at pyodide.asm.wasm:0x3dcd2f
    at pyodide.asm.wasm:0x3dc5f5
    at pyodide.asm.wasm:0x29f1bc
    at pyodide.asm.wasm:0x2a4cf1
    at pyodide.asm.wasm:0x1c3806
    at pyodide.asm.wasm:0x1c4570
API.fatal_error @ pyodide.asm.js:10
API.maybe_fatal_error @ pyodide.asm.js:10
callPyObjectKwargs @ pyodide.asm.js:10
Module.callPyObjectMaybePromising @ pyodide.asm.js:10
wrapper @ pyodide.asm.js:10
Kn.e.port1.onmessage @ pyodide.asm.js:10
pyodide.asm.js:10 Stack (most recent call first):
pyodide.asm.js:10   File "<frozen importlib._bootstrap_external>", line 147 in _path_stat
pyodide.asm.js:10   File "<frozen importlib._bootstrap_external>", line 153 in _path_is_mode_type
pyodide.asm.js:10   File "<frozen importlib._bootstrap_external>", line 168 in _path_isdir
pyodide.asm.js:10   File "<frozen importlib._bootstrap_external>", line 1621 in find_spec
pyodide.asm.js:10   File "<frozen importlib._bootstrap_external>", line 1498 in _get_spec
pyodide.asm.js:10   File "<frozen importlib._bootstrap_external>", line 1524 in find_spec
pyodide.asm.js:10   File "<frozen importlib._bootstrap>", line 1262 in _find_spec
pyodide.asm.js:10   File "<frozen importlib._bootstrap>", line 1322 in _find_and_load_unlocked
pyodide.asm.js:10   File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
pyodide.asm.js:10   File "<ipython-input-1-3e1c33dc1f55>", line 1 in <module>
pyodide.asm.js:10   File "/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3577 in run_code
pyodide.asm.js:10   File "/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3517 in run_ast_nodes
pyodide.asm.js:10   File "/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3334 in run_cell_async
pyodide.asm.js:10   File "/lib/python3.12/site-packages/IPython/core/async_helpers.py", line 129 in _pseudo_sync_runner
pyodide.asm.js:10   File "/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3130 in _run_cell
pyodide.asm.js:10   File "/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3075 in run_cell
pyodide.asm.js:10   File "/lib/python3.12/site-packages/pyodide_kernel/kernel.py", line 103 in run
pyodide.asm.js:10   File "/lib/python312.zip/asyncio/events.py", line 84 in _run
pyodide.asm.js:10   File "/lib/python312.zip/pyodide/webloop.py", line 332 in run_handle
pyodide.asm.js:10 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getTime')
    at Object.doStat (pyodide.asm.js:10:233214)
    at ___syscall_stat64 (pyodide.asm.js:10:274177)
    at pyodide.asm.wasm:0x49711e
    at pyodide.asm.wasm:0x4b0d76
    at pyodide.asm.wasm:0x3dcd2f
    at pyodide.asm.wasm:0x3dc5f5
    at pyodide.asm.wasm:0x29f1bc
    at pyodide.asm.wasm:0x2a4cf1
    at pyodide.asm.wasm:0x1c3806
    at pyodide.asm.wasm:0x1c4570
doStat @ pyodide.asm.js:10
___syscall_stat64 @ pyodide.asm.js:10
$fstatat @ pyodide.asm.wasm:0x49711e
$stat @ pyodide.asm.wasm:0x4b0d76
$func6514 @ pyodide.asm.wasm:0x3dcd2f
$func6511 @ pyodide.asm.wasm:0x3dc5f5
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x29f1bc
$func3407 @ pyodide.asm.wasm:0x2a4cf1
$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x1c3806
$func1161 @ pyodide.asm.wasm:0x1c4570
$PyObject_CallMethodObjArgs @ pyodide.asm.wasm:0x1c434c
$PyImport_ImportModuleLevelObject @ pyodide.asm.wasm:0x2dbbc9
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x2a2798
$PyEval_EvalCode @ pyodide.asm.wasm:0x295f35
$func3371 @ pyodide.asm.wasm:0x293b29
$func2165 @ pyodide.asm.wasm:0x20a621
$PyObject_Vectorcall @ pyodide.asm.wasm:0x1c346f
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x2a0457
$func1525 @ pyodide.asm.wasm:0x1d928c
$func1518 @ pyodide.asm.wasm:0x1d8b32
$func1548 @ pyodide.asm.wasm:0x1da130
_PyEM_TrampolineCall_JS @ pyodide.asm.js:10
$func1314 @ pyodide.asm.wasm:0x1ce138
$PyObject_Vectorcall @ pyodide.asm.wasm:0x1c346f
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x2a0457
$func1525 @ pyodide.asm.wasm:0x1d928c
$func1547 @ pyodide.asm.wasm:0x1da122
$PyIter_Send @ pyodide.asm.wasm:0x1aeea6
$func4997 @ pyodide.asm.wasm:0x345773
$func4995 @ pyodide.asm.wasm:0x3454b8
$func5003 @ pyodide.asm.wasm:0x346b82
_PyEM_TrampolineCall_JS @ pyodide.asm.js:10
$func2167 @ pyodide.asm.wasm:0x20a922
$func3600 @ pyodide.asm.wasm:0x2c79c0
$func2165 @ pyodide.asm.wasm:0x20a621
$func1140 @ pyodide.asm.wasm:0x1c3339
$_PyObject_Call @ pyodide.asm.wasm:0x1c3648
$PyObject_Call @ pyodide.asm.wasm:0x1c36c6
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x29e6fa
$func3407 @ pyodide.asm.wasm:0x2a4cf1
$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x1c3806
$PyObject_Vectorcall @ pyodide.asm.wasm:0x1c346f
$_pyproxy_apply @ pyodide.asm.wasm:0x176af6
callPyObjectKwargs @ pyodide.asm.js:10
Module.callPyObjectMaybePromising @ pyodide.asm.js:10
wrapper @ pyodide.asm.js:10
Kn.e.port1.onmessage @ pyodide.asm.js:10
pyodide.asm.js:10 Loaded joblib, numpy, openblas, scikit-learn, scipy, threadpoolctl
</pre>
</details>

**Comment by krassowski** [comment]
It seems that passing `code=` is not required to reproduce. It seems sufficient to have to REPL iframes embedded.

**Comment by jtpio** [comment]
Thanks @krassowski for reporting.

Does this also happen in the JupyterLab interface when starting multiple kernels?

> It's surprising as this also happens if these are in iframes but I guess it is using the same service worker?

Most likely yes, if the iframes are served via the same domain. Maybe it could be worth trying after disabling the Service Worker to check if it might be the cause of the issue?

**Comment by krassowski** [comment]
I tried enabling the cache but it did not help. TO disable the service worker do I need to enable Shared Array buffer or is there a different setting for it?

**Comment by jtpio** [comment]
It can be disabled via the `disabledExtensions`: https://jupyterlite.readthedocs.io/en/stable/howto/configure/advanced/extensions.html#disabling-extensions-at-runtime

**Comment by krassowski** [comment]
I could not get starting two kernels to work in JupyterLab interface either, but when I tried now I got a different error, the one reported in https://github.com/jupyterlite/jupyterlite/issues/1243 and I saw it before too. Maybe these are two manifestations of the same issue?

![image](https://github.com/user-attachments/assets/cba00563-88be-443e-9afd-59487d1edea1)

**Comment by krassowski** [comment]
I also have this at the top:

```
/jupyterlite-demo/server-proxy/servers-info?1723800766955:1 
       Failed to load resource: the server responded with a status of 404 ()
```

I think it is unrelated, but I know that uncaught errors can cascade and cause problems down the line so just noting this down in case if it might be helpful

**Comment by jtpio** [comment]
> I also have this at the top:

That one is likely because the build environment has the `jupyter-server-proxy` extension installed, which is then picked up at `jupyter lite build` time.

**Comment by datakurre** [comment]
@krassowski Did you solve this issue? l don't think I have `jupyter-server-proxy` (find no trace about it), but I am able to see this by trying to open the same deployment in two tabs at the same time.

**Comment by doelgonzo** [comment]
> [@krassowski](https://github.com/krassowski) Did you solve this issue? l don't think I have `jupyter-server-proxy` (find no trace about it), but I am able to see this by trying to open the same deployment in two tabs at the same time.

+1 Seeing this too

**Comment by jtpio** [comment]
Closing as (likely) fixed. Please feel free to re-open if the issue still happens, thanks!
