### ISSUE TITLE
`Ship additional Pyodide wheels at build time` does not work

### ISSUE THREAD

**Issue by jmrohwer** [jupyterlite/jupyterlite#1502]
Related issue #1023 although the problem is not solved in that issue.

## Description

I am trying to create a JupyterLite environment and ship two custom-compiled pyodide wasm32 wheels with the environment. The wheels have been compiled in a custom pyodide environment and tested in a pyodide shell, and they work.

The steps listed in https://jupyterlite.readthedocs.io/en/latest/howto/pyodide/wheels.html#adding-wheels-to-the-pyodide-kernel do not work as outlined below.

In the mean time I have managed to manually create the environment and it works, but it involved doing a lot of stuff by hand which is not suitable for production workflows. For reference the environment is available here: https://pysces.github.io/try/

## Reproduce

1. Copy wheels to `lite-dir/pypi`
2. Run `jupyter-lite build`
3. The site gets built but the wheels are not copied and not available from within the JupyterLite environment   
   - `_output/pypi` does not get created
   - there are no wheels under `_output`
   - there is no index `all.json` created
   - the wheels are not added to `pipliteUrls` in `jupyter-lite.json`

## Expected behavior

All of the above should have happened according to the documentation.

## Alternative approach

I also tried directly using the `--piplite-wheels` flag:
```bash
jupyter-lite build --piplite-wheels pypi/pysces-1.2.3.dev0-cp312-cp312-pyodide_2024_0_wasm32.whl
```
However, this resulted in the following traceback:
```python
[LiteBuildApp] WARNING | [lite] [addon] [jupyterlite-pyodide-kernel-piplite] FAIL
Traceback (most recent call last):
  File "/home/jr/.virtualenvs/jupyterlite/lib/python3.12/site-packages/traitlets/traitlets.py", line 632, in get
    value = obj._trait_values[self.name]
            ~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: '_addons'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jr/.virtualenvs/jupyterlite/lib/python3.12/site-packages/jupyterlite_core/manager.py", line 75, in create_addons
    addon_inst = addon_implementation(**addon_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jr/.virtualenvs/jupyterlite/lib/python3.12/site-packages/jupyterlite_core/addons/base.py", line 50, in __init__
    super().__init__(*args, **kwargs)
  File "/home/jr/.virtualenvs/jupyterlite/lib/python3.12/site-packages/traitlets/config/configurable.py", line 116, in __init__
    self.config = config
    ^^^^^^^^^^^
  File "/home/jr/.virtualenvs/jupyterlite/lib/python3.12/site-packages/traitlets/traitlets.py", line 716, in __set__
    self.set(obj, value)
  File "/home/jr/.virtualenvs/jupyterlite/lib/python3.12/site-packages/traitlets/traitlets.py", line 706, in set
    obj._notify_trait(self.name, old_value, new_value)
  File "/home/jr/.virtualenvs/jupyterlite/lib/python3.12/site-packages/traitlets/traitlets.py", line 1513, in _notify_trait
    self.notify_change(
  File "/home/jr/.virtualenvs/jupyterlite/lib/python3.12/site-packages/traitlets/traitlets.py", line 1525, in notify_change
    return self._notify_observers(change)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jr/.virtualenvs/jupyterlite/lib/python3.12/site-packages/traitlets/traitlets.py", line 1568, in _notify_observers
    c(event)
  File "/home/jr/.virtualenvs/jupyterlite/lib/python3.12/site-packages/traitlets/traitlets.py", line 1143, in compatible_observer
    return func(self, change)
           ^^^^^^^^^^^^^^^^^^
  File "/home/jr/.virtualenvs/jupyterlite/lib/python3.12/site-packages/traitlets/config/configurable.py", line 232, in _config_changed
    self._load_config(change.new, traits=traits, section_names=section_names)
  File "/home/jr/.virtualenvs/jupyterlite/lib/python3.12/site-packages/traitlets/config/configurable.py", line 193, in _load_config
    setattr(self, name, deepcopy(config_value))
  File "/home/jr/.virtualenvs/jupyterlite/lib/python3.12/site-packages/traitlets/traitlets.py", line 716, in __set__
    self.set(obj, value)
  File "/home/jr/.virtualenvs/jupyterlite/lib/python3.12/site-packages/traitlets/traitlets.py", line 690, in set
    new_value = self._validate(obj, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jr/.virtualenvs/jupyterlite/lib/python3.12/site-packages/traitlets/traitlets.py", line 722, in _validate
    value = self.validate(obj, value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jr/.virtualenvs/jupyterlite/lib/python3.12/site-packages/traitlets/traitlets.py", line 3478, in validate
    value = super().validate(obj, value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jr/.virtualenvs/jupyterlite/lib/python3.12/site-packages/traitlets/traitlets.py", line 2311, in validate
    self.error(obj, value)
  File "/home/jr/.virtualenvs/jupyterlite/lib/python3.12/site-packages/traitlets/traitlets.py", line 831, in error
    raise TraitError(e)
traitlets.traitlets.TraitError: The 'piplite_urls' trait of a PipliteAddon instance expected a tuple, not the str 'pypi/pysces-1.2.3.dev0-cp312-cp312-pyodide_2024_0_wasm32.whl'.
```
I am not sure what the structure of the expected tuple should be.

## How I got it to work:

1. Create the bare site (without additional wheels).
2. Copy the wheels by hand to `_output/extensions/@jupyterlite/pyodide-kernel-extension/static/pypi/` (note, **not** `_output/pypi` (this directory already contained some other wheels used by the kernel, i.e. `ipykernel`, `piplite`, `pyodide_kernel`, `widgetsnbextension`).
3. Update `_output/extensions/@jupyterlite/pyodide-kernel-extension/static/pypi/all.json` **by hand** including the filenames, sha256sum and md5sum of the added wheels.

## Indexing of wheels

I also could not get the indexing of the new wheels to work. According to https://jupyterlite.readthedocs.io/en/latest/howto/pyodide/wheels.html#ship-additional-pyodide-wheels-at-build-time with additional information in #1023 I tried unsuccessfully:
```bash
~/src/pysces-jupyterlite/pypi via jupyterlite 
➜ ls -l
total 4468
-rw-r--r-- 1 jr jr  907790 Oct 17 12:03 pysces-1.2.3.dev0-cp312-cp312-pyodide_2024_0_wasm32.whl
-rw-r--r-- 1 jr jr 3664038 Oct 17 10:15 python_libsbml-5.20.4-cp312-cp312-pyodide_2024_0_wasm32.whl

~/src/pysces-jupyterlite/pypi via jupyterlite 
➜ jupyter-piplite index 
Traceback (most recent call last):
  File "/home/jr/.virtualenvs/jupyterlite/bin/jupyter-piplite", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/jr/.virtualenvs/jupyterlite/lib/python3.12/site-packages/jupyter_core/application.py", line 283, in launch_instance
    super().launch_instance(argv=argv, **kwargs)
  File "/home/jr/.virtualenvs/jupyterlite/lib/python3.12/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/home/jr/.virtualenvs/jupyterlite/lib/python3.12/site-packages/jupyter_core/application.py", line 270, in start
    self.subapp.start()
  File "/home/jr/.virtualenvs/jupyterlite/lib/python3.12/site-packages/jupyterlite_pyodide_kernel/app.py", line 46, in start
    raise ValueError(f"no supported wheels found in {self.wheel_dir}")
ValueError: no supported wheels found in /home/jr/src/pysces-jupyterlite/pypi
```

The wheels are perfectly compatible and run in a pyodide environment as well as the site I created by hand (see above).

## Context

- JupyterLite version: 0.4.2
- Python version: 3.12.6
- Operating System and version: Manjaro Linux, kernel 6.6.54
- Browser and version: Firefox 131.0.2

<details><summary>Browser Output</summary>
Not relevant, the bug pertains to building the site.
</details>

**Comment by tubaman** [comment]
I've confirmed "How I got it to work" above.  You can also [add the list of wheels](https://jupyterlite.readthedocs.io/en/stable/howto/configure/advanced/offline.html#configure-the-piplite-wheels) to `juputer_lite_config.json`

**Comment by sadianliaoer** [comment]
I'm having the same problem. How can I solve it? Thank you.

**Comment by tubaman** [comment]
This works for me now with pyodide-kernel 0.6.1

`jupyter lite build --piplite-wheels=~/sandboxes/jupyterlite-tampermonkey/dist/tampermonkey-0.0.4-py3-none-any.whl`
