### ISSUE TITLE
Notebooks are not completely shown/loaded in jupyterlite?

### ISSUE THREAD

**Issue by tBuLi** [jupyterlite/jupyterlite#1532]
## Description

Some notebooks seem to not be shown/loaded completely by jupyterlite. For an example, see the following link: https://tbuli.github.io/teahouse/lab/index.html?path=exercises%2Fspider6.ipynb. The full notebook can be found on github here: https://github.com/tBuLi/teahouse/blob/main/content/exercises/spider6.ipynb.

This demonstrates that only the first "half" of the notebook is shown, while the rest has vanished.

In the console I see the following errors from windowedlist.js for the problematic files:
```
Uncaught Error: Sizer 1 has incorrect offset.
    at Y._getItemMetadata (windowedlist.js:505:27)
    at Y._findNearestItemBinarySearch (windowedlist.js:529:40)
    at Y._findNearestItem (windowedlist.js:517:25)
    at Y._getStartIndexForOffset (windowedlist.js:573:21)
    at Y._getRangeToRender (windowedlist.js:561:33)
    at Y.getRangeToRender (windowedlist.js:375:35)
    at me._update (windowedlist.js:1012:47)
    at windowedlist.js:901:26
```
## Reproduce

I'm unsure on how to trigger this bug, because the notebook https://tbuli.github.io/teahouse/lab/index.html?path=exercises%2Fspider2.ipynb in the same directory loads fine. In general it seems most of my notebooks load just fine, but there are several in this project that don't work.

I've experienced this problem in Chrome and Brave on windows and Chrome and Safari on Mac, so it seems consistent.

## Context

- JupyterLite version: 0.4.4
- Operating System and version: Windows and Mac
 Full requirement.txt of my project:
```
# Core modules (mandatory)
jupyterlite-core==0.4.4
jupyterlab~=4.2.6
notebook~=7.2.2


# Python kernel (optional)
jupyterlite-pyodide-kernel==0.4.4

# JavaScript kernel (optional)
jupyterlite-javascript-kernel==0.3.0

# JupyterLab: dark theme
jupyterlab-night
# JupyterLab: Miami nights theme (optional)
jupyterlab_miami_nights

# Customized launcher
jupyter_app_launcher

# Teahouse dependencies
anywidget==0.9.9
```

Edit: since the original post I have upgraded to 0.4.4 but the problem persists, although not on the same files, so I have changed the links to examples. I also added the error from the browser console.

**Comment by tBuLi** [comment]
Update: same problem also happens if I take the failing notebook and upload it to https://jupyterlite.github.io/xeus-python-demo and run from there.

**Comment by krassowski** [comment]
https://tbuli.github.io/teahouse/lab/index.html?path=exercises%2Fspider6.ipynb works for me on 4k screen. What is your screen resolution?

**Comment by krassowski** [comment]
Ok, I can reproduce it after resizing the window down. This is super helpful for me as it is a great reproducer for https://github.com/jupyterlab/jupyterlab/issues/17023

**Comment by krassowski** [comment]
That said, rebuilding with JupyterLab 4.3.2 assets might solve this problem. I guess https://github.com/jupyterlite/jupyterlite/pull/1514 could help here.

**Comment by tBuLi** [comment]
Thanks for your helpful reply @krassowski. First about my resolution, I'm also using 4k but then I just realized I'm usually a bit zoomed in because I though the default fonts were a bit small. So then I zoomed out and it turns out that at 67% or smaller the bug disappears and the whole notebook loads!

(So that's at least a workaround for me now because I plan to teach with these notebooks tomorrow at a workshop.)

My version numbers were based on the pyodide readme, but now I also followed your advice (locally) to upgrade to the following packages:
```
# Core modules (mandatory)
jupyterlite-core==0.4.4
jupyterlab==4.3.2
notebook~=7.3.1


# Python kernel (optional)
jupyterlite-pyodide-kernel==0.4.4

# JavaScript kernel (optional)
jupyterlite-javascript-kernel==0.3.0

# JupyterLab: dark theme
jupyterlab-night
# JupyterLab: Miami nights theme (optional)
jupyterlab_miami_nights

# Customized launcher
jupyter_app_launcher

# Teahouse dependencies
anywidget==0.9.9
```
But unfortunately even with 4.3.2 the problem persists.

**Comment by krassowski** [comment]
Another workaround: go to Settings → Notebook → Windowing → `none` (`defer` may work too) → save.

**Comment by tBuLi** [comment]
Both of those work and solve the problem, thanks for the tip. Is there anyway that I can e.g. add this to a config json file or do something else, to make this the default setting?

**Comment by krassowski** [comment]
Yes, you can set it via `overrides.json` https://jupyterlite.readthedocs.io/en/stable/howto/configure/config_files.html#overrides-json

**Comment by tBuLi** [comment]
I'm sorry to be a bit daft but I don't know how, I was actually looking at that same page now :P. These config files are still a bit magical to me, could you give me more details on what the names of the fields are?

**Comment by jtpio** [comment]
@tBuLi maybe this will fix it?

```json
{
  "@jupyterlab/notebook-extension:tracker": {"windowingMode": "defer"}
}
```

**Comment by tBuLi** [comment]
That did the trick @jtpio, thanks for your help!
