### ISSUE TITLE
Firefox: OverflowError: Python int too large to convert to C long

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/jupyterlite#443]
## Description

There appears to be an issue with Pyolite and Firefox 97.0b2.

![image](https://user-images.githubusercontent.com/591645/149161263-29d0539c-be2c-4103-a998-89cdbadf1e05.png)

## Reproduce

Using `0.1.0a19` locally:

```
PythonError: Traceback (most recent call last):
  File "/lib/python3.9/site-packages/pyolite/patches.py", line 53, in apply_patches
    patch()
  File "/lib/python3.9/site-packages/pyolite/patches.py", line 9, in patch_matplotlib
    import matplotlib.pyplot
  File "/lib/python3.9/site-packages/matplotlib/__init__.py", line 107, in <module>
    from . import cbook, rcsetup
  File "/lib/python3.9/site-packages/matplotlib/cbook/__init__.py", line 28, in <module>
    import numpy as np
  File "/lib/python3.9/site-packages/numpy/__init__.py", line 161, in <module>
    from . import random
  File "/lib/python3.9/site-packages/numpy/random/__init__.py", line 180, in <module>
    from . import _pickle
  File "/lib/python3.9/site-packages/numpy/random/_pickle.py", line 1, in <module>
    from .mtrand import RandomState
  File "mtrand.pyx", line 1, in init numpy.random.mtrand
  File "bit_generator.pyx", line 1, in init numpy.random.bit_generator
  File "_common.pyx", line 20, in init numpy.random._common
OverflowError: Python int too large to convert to C long

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/lib/python3.9/site-packages/_pyodide/_base.py", line 494, in eval_code_async
    await CodeRunner(
  File "/lib/python3.9/site-packages/_pyodide/_base.py", line 347, in run_async
    await coroutine
  File "<exec>", line 15, in <module>
  File "/lib/python3.9/site-packages/pyolite/__init__.py", line 16, in <module>
    patches.apply_patches()
  File "/lib/python3.9/site-packages/pyolite/patches.py", line 55, in apply_patches
    warnings.warn("failed to apply patch", patch, err)
TypeError: 'OverflowError' object cannot be interpreted as an integer
```

## Expected behavior

Should work in Firefox.

## Context

- JupyterLite version: 0.1.0a19
- Operating System and version: Ubuntu 20.04
- Browser and version: Firefox Developer Edition 97.0b2

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by bollwyvl** [comment]
Works in FF 95.0.1 on ubuntu from the canonical repos. I'd reckon this worth reporting upstream to pyodide if it persists on their [REPL](https://pyodide.org/en/stable/console.html)... or even firefox.

We _could_ start using some selenium stuff against hot browser versions, but one runs the risk of needing a cascade of unreleased dev tools.

**Comment by jtpio** [comment]
I can confirm this is working on Firefox 95.0.1 on Ubuntu:

![image](https://user-images.githubusercontent.com/591645/149170651-4ee5c1ac-46c3-4a0a-afca-9ad80460faca.png)

**Comment by bollwyvl** [comment]
Still haven't seen this come up, guess re re-open if it does appear!

**Comment by jtpio** [comment]
I can confirm this works fine in Firefox Developer Edition (99.0b3):

![image](https://user-images.githubusercontent.com/591645/158126145-6e043b23-cd15-46d3-85c2-a9ed673005f6.png)


So this might have just been a transient issue in some of the Firefox betas.
