### ISSUE TITLE
Can't Interrupt Cell Execution in Python Kernel

### ISSUE THREAD

**Issue by brendan0powers** [jupyterlite/jupyterlite#459]
## Description

It seems like interrupting cell execution isn't implemented. If a cell is busy, and I click the "stop" button, nothing happens.
If a cell is running a loop or awaiting some resource, I need to restart the kernel to get control back.

I'm not super familiar with how this works in IPython, but I wonder if the pyodide implementation makes this tricky?
I might have some time to help implement a fix, so if you have any suggestions on where to start, let me know!

## Reproduce

Run a cell with this code:
```python
while True:
    pass
```

Click the interrupt button in the toolbar, and nothing happens.

## Expected behavior

A keyboard interrupt exception should be thrown, and the kernel should become idle.

## Context

- JupyterLite version: 0.1.0-alpha.20
- Operating System and version: MacOs 10.15.7
- Browser and version: Chrome 97.0.4692.71

**Comment by bollwyvl** [comment]
Having a go at it upstream on the [pyodide console](https://pyodide.org/en/stable/console.html) suggests we can't really do much about it...

**Comment by bollwyvl** [comment]
Oof, on the contrary, we can, but it requires a WebWorker (which we use, hooray) and `SharedArrayBuffer` (which we haven't had to yet, hmmm):

https://pyodide.org/en/latest/usage/keyboard-interrupts.html

We probably need to hook this  down in the [kernel](https://github.com/jupyterlite/jupyterlite/blob/main/packages/pyolite-kernel/src/kernel.ts)  or [worker](https://github.com/jupyterlite/jupyterlite/blob/main/packages/pyolite-kernel/src/worker.ts) .

**Comment by brendan0powers** [comment]
I was digging a little deeper on this, and it does seem like there is a way to implement this, although it has limitations.
https://pyodide.org/en/stable/usage/keyboard-interrupts.html
Basically, we'd use a SharedArrayBuffer to signal a keyboard interrupt from the main thread. It would look something like this.

1) Wait for the kernel to become ready
2) In the main thread, create an SharedArrayBuffer of size, 1. Pass is to the worker via postMessage()
    * Browser support for SharedArrayBuffer is new, and certain HTTP headers need to be set, so we'd need a way to fail here and notify the user somehow, perhaps in the log?
3) In the worker, call pyodide.setInterruptBuffer()
4) Add a new route for kernel interrupts to the server, route the message to the kernel in the same way as a kernel restart request.
5) Set the value of the SharedArrayBuffer to 2 (Interrupt Signal)
6) A KeyboardInterruptException is thrown, the same way it would for a normal python kernel.

If python is awaiting some javascript, we'd need to call pyodide.checkInterrupt(), and then handle any dangling promises/comms replies.

The big limitation with this approach is that you need support for SharedArrayBuffer in the browser, and the security constraints for the API need to be met.

**Comment by brendan0powers** [comment]
If you think this is a reasonable approach, I'd be happy to file a PR.

**Comment by bollwyvl** [comment]
It's definitely worth trying... At worst, we could make it opt-out, as
we've done with e.g. pypi fallback. But if it works on e.g.
readthedocs/gitlab|hub pages, it's worth doing, and being enabled by
default.

**Comment by brendan0powers** [comment]
The security constraints for SharedArrayBuffer are pretty restrictive. See here for more detail: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer/Planned_changes

There is no way to set these headers on Github pages or readthedocs, and they are not set by default.

**Comment by bollwyvl** [comment]
> There is no way to set these headers 

Ah, but there _is_, and it's down a route we've wanted to go for some time, namely a ServiceWorker, as hinted at by #137:

https://dev.to/stefnotch/enabling-coop-coep-without-touching-the-server-2d3n

(by the by: the object thing that author was building is _raaaad_: https://stefnotch.github.io/quantum-sheet/)

Making the ServiceWorker properly configurable and upgradeable is a probably a pretty big lift, but is ultimately where we must plan on going, given the size of the assets of even our baseline UI, much less pyodide+dog.

At any rate: for those that _can_ control their own headers, I guess i might be nice, but given the above, would have to be opt-in.

**Comment by brendan0powers** [comment]
Wow, that's pretty cool, I'm a little surprised that works. I still need this for my use case, so I'll try and see if I can implement it. Given that we can detect if SharedArrayBuffers are available, does it need to be opt-in? If the headers are present, the stop button will work, if they are not, it will just behave as before (Perhaps with a warning printed in the console?).

Also, the author bundled his service worker into a re-usable package. It's possible it could be used until the service worker PR has landed: https://github.com/gzuidhof/coi-serviceworker

**Comment by bollwyvl** [comment]
> does it need to be opt-in

It all depends on the failure modes... site owners get quite sensitive about extra errors they see in the console...

> a warning printed in the console

...but the average end user won't look here to see that's why they can't interrupt stuff... it's kind of the worst of all worlds.

> service worker into a re-usable package.

it's good to have a reference, but i think we're going to want/need a fair amount of control over how it works. a robust serviceworker is going to have a _far_ greater impact on most end users' experiences than interruptible python kernels, so would prefer to see ServiceWorker landed, well... but wouldn't anticipate the author of #137 picking it back up (pretty busy dude).

Another option, of course, would be for you to subclass the kernel to investigate it for your needs: we have taken that approach on [pidgy](https://github.com/deathbeds/pidgy/) which actually is another kernel.

**Comment by brendan0powers** [comment]
I did a quick implementation, and as long as you have the headers set correctly, it works. It doesn't work on localhost by default though, which I think it should. This might be an oversight in Chrome.

A tight loop like this is interrupted as you'd expect:
```python
while True:
  pass
```
But, if the kernel is awaiting a javascript function, in this loop for example:
```python
while True:
  await asyncio.sleep(1)
```
The KeyboardInterrupt gets thrown in https://github.com/pyodide/pyodide/blob/main/src/py/pyodide/webloop.py#L148
At that point, the exception propagates untill it reaches javascript, at the setTimeout callback. This leaves the kernel in the Busy state. I'm not entirely sure how we should handle this exception, or why it would leave the kernel in the busy state. It's possible pyodide should be catching this exception, and treating the promise as if it were canceled? 

Here's the stack trace:
```
pyodide.asm.js:14 Uncaught PythonError: Traceback (most recent call last):
  File "/lib/python3.9/site-packages/pyodide/webloop.py", line 148, in run_handle
    if h.cancelled():
  File "/lib/python3.9/asyncio/events.py", line 75, in cancelled
    def cancelled(self):
KeyboardInterrupt

    at new_error (pyodide.asm.js:14:247183)
    at pyodide.asm.wasm:0xe6eb0
    at pyodide.asm.wasm:0xe6fae
    at Object.Module._pythonexc2js (pyodide.asm.js:14:944230)
    at Object.Module.callPyObjectKwargs (pyproxy.gen.js:391:12)
    at Object.Module.callPyObject (pyproxy.gen.js:397:17)
    at wrapper (pyodide.asm.js:14:215278)
```

**Comment by bollwyvl** [comment]
Maybe we need some stuff like this:

https://pyodide.org/en/stable/usage/keyboard-interrupts.html#allowing-javascript-code-to-be-interrupted

**Comment by brendan0powers** [comment]
Yeah, I'm not sure how to apply it in this context. Python may call out to JS at any time, and await a promise. There's no common code that sits in between that JupyterLite controls. asyncio.sleep() is a good example. This turns into a setTimeout call, with a callback function. I think I'll try to create a simple use-case and file an issue with pyodide, and see what they suggest.

Do you have a sense of how much work there is to be done on the serviceworker PR? Would it be possible for someone else to pick this up and finish it?

**Comment by brendan0powers** [comment]
I've created a WIP PR #460. 

I've also created a test case for when an interrupt occurs while python is awaiting a function. I've verified that if that happens, the promise returned from runPythonAsync() never resolves. It's possible I'm still missing a step, but in either case, I'll file an issue with pyodide.

For reference, here's a JSFiddle that reproduces the issue: https://jsfiddle.net/jhb4d8s1/50/

**Comment by brendan0powers** [comment]
I filed a pyodide issue: https://github.com/pyodide/pyodide/issues/2141

**Comment by jtpio** [comment]
> and SharedArrayBuffer (which we haven't had to yet, hmmm)

For reference we were able to dodge it when compiling the xeus lua kernel to wasm (xref https://github.com/jupyterlite/xeus-lua-kernel/pull/14)

**Comment by brendan0powers** [comment]
If I understand the PR, I don't think that technique will work in this case. WASM shared threads use SharedArrayBuffers to provide a unified memory space. The PR disables multithreading in xeus, and avoids the use of the buffers.

**Comment by jtpio** [comment]
It should now be possible to experiment with this again as a follow-up to https://github.com/jupyterlite/jupyterlite/pull/1383, and have it enabled if `SharedArrayBuffer` is enabled on the page.

**Comment by ogrisel** [comment]
I just wanted to comment that as an occasional jupyterlite user, I would vote to bump the priority of this issue (but I do not have the skills to contribute a PR myself).

**Comment by krassowski** [comment]
I opened two PRs:
- https://github.com/jupyterlite/jupyterlite/pull/1683 to provide basic "stop after next" functionality
- https://github.com/jupyterlab/jupyterlab/pull/17684 to add types for interrupt messages

For the full interrupt support I have some drafts locally but I am yet to build a full mental model of message flow (I think I am getting close). I am pursuing sending `interrupt_request` to kernels and receiving back `interrupt_reply` and looking into implementation in `pyodide-kernel` and in `jupyterlite`. I do not have a functional solution yet. These are standard messages in Jupyter Messaging protocol v5.3 (though the default message factory in JupyterLab marks messages as 5.2, another thing we should probably change in preparation to solving this).
