### ISSUE TITLE
Hitting KeyError: mathjax_dir, for any "jupyter lite <>" commands 

### ISSUE THREAD

**Issue by pnsvk** [jupyterlite/jupyterlite#470]
After successful installation of jupyterlite[all], any "jupyter lite <>" command from the command-line on windows hits the below errors. 

```
$ jupyter lite status
Traceback (most recent call last):
    File "e:\venv\lib\site-packages\traitlets\traitlets.py", line 528, in get
        value = obj._trait_values[self.name
KeyError: 'lite_manager'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
    File "e:\venv\lib\site-packages\traitlets\traitlets.py", line 528, in get
        value = obj._trait_values[self.name]
KeyError: 'mathjax_dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
    File "C:\Python\3.7.0\lib\runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
    File "C:\Python\3.7.0\lib\runpy.py, line 85, in _run_code
        exec(code, run_globals)
    File "E:\venv\Scripts\jupyter-lite.EXE\__main__.py", line 7, in <module>
    File "e:\venv\lib\site-packages\jupyter_core\application.js", line 264, in launch_instance
        return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
    File "e:\venv\lib\site-packages\traitlets\config\application.py", line 664, in launch_instance
        app.start()
    File "e:\venv\lib\site-packages\jupyter_core\application.py", line 253, in start
        self.subapp.start()
    File "e:\venv\lib\site-packages\jupyterlite\app.py", line 176, in start
        super().start()
    File "e:\venv\lib\site-packages\jupyterlite\app.py", line 127, in start
        super().start()
    File "e:\venv\lib\site-packages\jupyterlite\app.py", line 117, in start
        self.lite_manager.initialize()
    File "e:\venv\lib\site-packages\traitlets\traitlets.py", line 556, in __get__
        return self.get(obj, cls)
    File "e:\venv\lib\site-packages\traitlets\traitlets.py", line 535, in get
        value = self._validate(obj, dynamic_default())
    File "e:\venv\lib\site-packages\jupyterlite\app.py", line 85, in _default_manager
        if self.mathjax_dir:
    File "e:\venv\lib\site-packages\traitlets\traitlets.py", line 556, in __get__
        return self.get(obj, cls)
    File "e:\venv\lib\site-packages\traitlets\traitlets.py", line 534, in get
        % (self.name, obj))
traitlets.traitlets.TraitError: No default value found for mathjax_dir trait of <jupyterlite.app.LiteStatusApp object at 0x0000000001315290>
```

**Comment by bollwyvl** [comment]
Thanks, there may in fact be an issue with `mathjax_dir`.

can you drop the output of `pip list` for the rest of the version info?

**Comment by bollwyvl** [comment]
Closing due to inactivity.
