### ISSUE TITLE
HookWebpackError: ENOENT: no such file or directory, scandir

### ISSUE THREAD

**Issue by danielemoroni** [jupyterlite/jupyterlite#553]
## Description

I did a fresh download and install, and I get the error in the title.

## Reproduce

I literally followed the contributing guide. After downloading mambaforge:
1. git clone https://github.com/jupyterlite/jupyterlite
2. mamba env update --file .binder/environment.yml
3. mamba activate jupyterlite-dev
4. python -m pip install -r requirements-docs.txt -r requirements-lint.txt
5. doit

and I get the error

> .  build:js:app
yarn run v1.22.17
$ C:\Users\DanieleMoroni\Documents\dev\jupyterlite\node_modules\.bin\lerna run build:prod --scope @jupyterlite/app
lerna notice cli v4.0.0
lerna info versioning independent
lerna notice filter including "@jupyterlite/app"
lerna info filter [ '@jupyterlite/app' ]
lerna info Executing command in 1 package: "yarn run build:prod"
lerna ERR! yarn run build:prod exited 2 in '@jupyterlite/app'
lerna ERR! yarn run build:prod stdout:
$ yarn clean && yarn build --mode=production
$ rimraf build **/build
$ webpack --mode=production
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build:prod stderr:
[webpack-cli] ←[31mHookWebpackError: ENOENT: no such file or directory, scandir
    at makeWebpackError (C:\Users\DanieleMoroni\Documents\dev\jupyterlite\node_modules\webpack\lib\HookWebpackError.js:48:9)
    at C:\Users\DanieleMoroni\Documents\dev\jupyterlite\node_modules\webpack\lib\Compilation.js:3059:12
    at eval (eval at create (C:\Users\DanieleMoroni\Documents\dev\jupyterlite\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:23:1)
    at fn (C:\Users\DanieleMoroni\Documents\dev\jupyterlite\node_modules\webpack\lib\Compilation.js:480:17)
    at _next9 (eval at create (C:\Users\DanieleMoroni\Documents\dev\jupyterlite\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:21:1)
    at eval (eval at create (C:\Users\DanieleMoroni\Documents\dev\jupyterlite\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:37:1)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
-- inner error --
Error: ENOENT: no such file or directory, scandir
    at Object.readdirSync (fs.js:1047:3)
    at CacheBackend.provideSync (C:\Users\DanieleMoroni\Documents\dev\jupyterlite\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:233:32)
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    at WebpackFileSystem.listPaths (C:\Users\DanieleMoroni\Documents\dev\jupyterlite\node_modules\license-webpack-plugin\dist\WebpackFileSystem.js:78:24)
    at LicenseTextReader.readLicense (C:\Users\DanieleMoroni\Documents\dev\jupyterlite\node_modules\license-webpack-plugin\dist\LicenseTextReader.js:37:54)
    at PluginChunkReadHandler.processModule (C:\Users\DanieleMoroni\Documents\dev\jupyterlite\node_modules\license-webpack-plugin\dist\PluginChunkReadHandler.js:46:62)
    at C:\Users\DanieleMoroni\Documents\dev\jupyterlite\node_modules\license-webpack-plugin\dist\PluginChunkReadHandler.js:22:23
    at WebpackModuleFileIterator.internalCallback (C:\Users\DanieleMoroni\Documents\dev\jupyterlite\node_modules\license-webpack-plugin\dist\WebpackModuleFileIterator.js:25:13)
    at WebpackModuleFileIterator.iterateFiles (C:\Users\DanieleMoroni\Documents\dev\jupyterlite\node_modules\license-webpack-plugin\dist\WebpackModuleFileIterator.js:10:9)
    at C:\Users\DanieleMoroni\Documents\dev\jupyterlite\node_modules\license-webpack-plugin\dist\PluginChunkReadHandler.js:20:32
    at WebpackChunkModuleIterator.iterateModules (C:\Users\DanieleMoroni\Documents\dev\jupyterlite\node_modules\license-webpack-plugin\dist\WebpackChunkModuleIterator.js:42:21)
caused by plugins in Compilation.hooks.processAssets
Error: ENOENT: no such file or directory, scandir
    at Object.readdirSync (fs.js:1047:3)
    at CacheBackend.provideSync (C:\Users\DanieleMoroni\Documents\dev\jupyterlite\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:233:32)
    at WebpackFileSystem.listPaths (C:\Users\DanieleMoroni\Documents\dev\jupyterlite\node_modules\license-webpack-plugin\dist\WebpackFileSystem.js:78:24)
    at LicenseTextReader.readLicense (C:\Users\DanieleMoroni\Documents\dev\jupyterlite\node_modules\license-webpack-plugin\dist\LicenseTextReader.js:37:54)
    at PluginChunkReadHandler.processModule (C:\Users\DanieleMoroni\Documents\dev\jupyterlite\node_modules\license-webpack-plugin\dist\PluginChunkReadHandler.js:46:62)
    at C:\Users\DanieleMoroni\Documents\dev\jupyterlite\node_modules\license-webpack-plugin\dist\PluginChunkReadHandler.js:22:23
    at WebpackModuleFileIterator.internalCallback (C:\Users\DanieleMoroni\Documents\dev\jupyterlite\node_modules\license-webpack-plugin\dist\WebpackModuleFileIterator.js:25:13)
    at WebpackModuleFileIterator.iterateFiles (C:\Users\DanieleMoroni\Documents\dev\jupyterlite\node_modules\license-webpack-plugin\dist\WebpackModuleFileIterator.js:10:9)
    at C:\Users\DanieleMoroni\Documents\dev\jupyterlite\node_modules\license-webpack-plugin\dist\PluginChunkReadHandler.js:20:32
    at WebpackChunkModuleIterator.iterateModules (C:\Users\DanieleMoroni\Documents\dev\jupyterlite\node_modules\license-webpack-plugin\dist\WebpackChunkModuleIterator.js:42:21)←[39m
error Command failed with exit code 2.
error Command failed with exit code 2.
lerna ERR! yarn run build:prod exited 2 in '@jupyterlite/app'
error Command failed with exit code 2.
TaskFailed - taskid:build:js:app
Command failed: '['C:\\Users\\DanieleMoroni\\mambaforge\\envs\\jupyterlite-dev\\Library\\bin\\yarn.cmd', 'lerna', 'run', 'build:prod', '--scope', '@jupyterlite/app']' returned 2

## Expected behavior

No build error

## Context

- JupyterLite version: v0.1.0b2, commit 65a47e6 from 14 Mar 2022
- Operating System and version: Windows 10 21H2
- Browser and version: n/a

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by bollwyvl** [comment]
It looks like this might in fact be a problem upstream: https://github.com/xz64/license-webpack-plugin/issues/111

In the short term: we could [skip adding that plugin on windows](https://github.com/jupyterlite/jupyterlite/blob/main/app/webpack.config.js#L274), knowing that it would not create the `build/third-party-licenses.json` file. This is fine, as our release-oriented python builds, which _are_ tested on windows, would continue to be built, once, on linux... and extensions would still report some licenses, likely.

Longer term: a PR for a CI job, running parallel to the "for real" `build` job, that just tries to do some basic dev stuff on windows: there's a good deal of the full build that hasn't been tested on windows _at all_, so we'd likely want to try the basics of e.g. `doit lint build`.

**Comment by bollwyvl** [comment]
We now have it working under CI on windows, skipping the license plugin: please pull again and give this a shot, and open a new issue for whatever else you might encounter: this is preferable to changing the issue name, which has strong SEO energy.

**Comment by danielemoroni** [comment]
Thank you, that worked!

I now get some errors at the env:lite stage, with a blocking error at env:lite:extensions, but that stage is after the build ones, so I can now spawn a working jupyterlite server. I'll open a separate non-urgent ticket for those errors.
