### ISSUE TITLE
Build errors at env:lite

### ISSUE THREAD

**Issue by danielemoroni** [jupyterlite/jupyterlite#560]
## Description

This follows up on this [issue ](https://github.com/jupyterlite/jupyterlite/issues/553). A clean download and install produces a working jupyterlite server, but some build errors appear.

## Reproduce

1. git clone https://github.com/jupyterlite/jupyterlite
2. mamba env update --file .binder/environment.yml
3. mamba activate jupyterlite-dev
4. python -m pip install -r requirements-docs.txt -r requirements-lint.txt
5. doit

and I get the errors

> .  env:lite:deps:p5.ipynb
Traceback (most recent call last):
  File "C:\mf\envs\jupyterlite-dev\Scripts\depfinder-script.py", line 9, in <module>
    sys.exit(cli())
  File "C:\mf\envs\jupyterlite-dev\lib\site-packages\depfinder\cli.py", line 228, in cli
    deps = notebook_path_to_dependencies(
  File "C:\mf\envs\jupyterlite-dev\lib\site-packages\depfinder\main.py", line 147, in notebook_path_to_dependencies
    deps_dict = get_imported_libs(codeblock, custom_namespaces=custom_namespaces).describe()
  File "C:\mf\envs\jupyterlite-dev\lib\site-packages\depfinder\inspection.py", line 278, in get_imported_libs
    tree = ast.parse(code)
  File "C:\mf\envs\jupyterlite-dev\lib\ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    var n = 4;
        ^
SyntaxError: invalid syntax
C:\jl\examples\p5.ipynb probably isn't python
.  env:lite:deps:plotly.ipynb
.  env:lite:deps:ipycanvas.ipynb
.  env:lite:deps:altair.ipynb
.  env:lite:deps:intro.ipynb
.  env:lite:deps:interactive-widgets.ipynb
.  env:lite:deps:renderers.ipynb
.  env:lite:deps:images.ipynb
.  env:lite:deps:ipyvuetify.ipynb
.  env:lite:deps:emscripten-filesystem.ipynb
.  env:lite:deps:matplotlib.ipynb
.  env:pyodide:packages
.  env:lite:deps:ipyleaflet.ipynb
.  env:lite:deps:python.ipynb
.  env:lite:deps:ipycytoscape.ipynb
.  env:lite:deps:javascript.ipynb
Traceback (most recent call last):
  File "C:\mf\envs\jupyterlite-dev\Scripts\depfinder-script.py", line 9, in <module>
    sys.exit(cli())
  File "C:\mf\envs\jupyterlite-dev\lib\site-packages\depfinder\cli.py", line 228, in cli
    deps = notebook_path_to_dependencies(
  File "C:\mf\envs\jupyterlite-dev\lib\site-packages\depfinder\main.py", line 147, in notebook_path_to_dependencies
    deps_dict = get_imported_libs(codeblock, custom_namespaces=custom_namespaces).describe()
  File "C:\mf\envs\jupyterlite-dev\lib\site-packages\depfinder\inspection.py", line 278, in get_imported_libs
    tree = ast.parse(code)
  File "C:\mf\envs\jupyterlite-dev\lib\ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    const delay = 2000;
          ^
SyntaxError: invalid syntax
C:\jl\examples\javascript.ipynb probably isn't python
.  env:lite:extensions
TaskError - taskid:env:lite:extensions
PythonAction Error
Traceback (most recent call last):
  File "C:\mf\envs\jupyterlite-dev\lib\site-packages\doit\action.py", line 437, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "C:\jl\dodo.py", line 1171, in sync_lite_config
    raw_lock = subprocess.check_output(["conda", "list", "--explicit"])
  File "C:\mf\envs\jupyterlite-dev\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\mf\envs\jupyterlite-dev\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\mf\envs\jupyterlite-dev\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\mf\envs\jupyterlite-dev\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

no big surprises for the p5.ipynb and javascript.ipynb, but the env:lite:extensions blocks the doit workflow. The error doesn't prevent from getting a working jupyterlite server by issuing 'yarn serve'.

## Expected behavior

No build errors

## Context

- JupyterLite version: v0.1.0b3
- Operating System and version: Windows 10, 21H2
- Browser and version: n/a

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by bollwyvl** [comment]
This kinda boils down to two, orthogonal concerns:

- _keeping the shipped software running on windows_
  - which i like to think we take pretty seriously
  - we _would_ block a feature that doesn't work on windows
    - or at least make it optional/opt-in
- _keep the dev pipeline working on windows_
  - which we kinda haven't cared about **at all**
  - some of this stuff barely works on _any_ computer
  - we would probably _not_ block shipping a cool feature that couldn't be _built_ on windows

in a number of cases, we've refactored things from the "dev" side of the house into the actual `jupyter lite` CLI (which also uses doit), and then windows-specific bugs are found through normal unit and integration testing.

> `python -m pip install -r requirements-docs.txt -r requirements-lint.txt`

i _believe_ all of these are already included in the `binder` env... and re-installing with `pip` very possibly could break things. _especially_ on windows, my patience for `pip` is... thin. it's tolerable on CI, as they are highly controlled, if idiosyncratic, environments... 

> blocks the doit workflow. 

what, precisely, are you trying to get up to running? the "default", unnamed task is just a placeholder for what binder does, but you can pick from any of the tasks in `doit list --all`. a perusal of the [doit docs](https://pydoit.org/) can help provide some context around why/how we're using it.

> No build errors

at some point there are diminishing returns on linux-using, volunteer maintainers trying to keep some of these things running on windows... the docs at the end of the default task needs rather a lot of stuff to work, and has _never_ been attempted on windows. That could be you!

But anyhow: i'm only going to fix-it-by-CI, which isn't in anybody's interest. The "Win Dev" CI we have in place is now, already, the slowest thing we test... we'd probably need a separate PR that moved that to "only merges to `main`" (again, see not blocking on dev).

> a working jupyterlite server

so i'd wager, to get to the examples site, there are some places where:
- instead of assuming that a command name will work on window, we need to `shutil.which()`
- maybe some more paths need to be resolved/escaped/cast to strings

**Comment by danielemoroni** [comment]
I get your points, thank you for the reply. I only flagged the doit errors to keep the community aware, just in case some other windows users comes up with the same question. I already achieved what I needed, a working jupyterlite server. If I get some time I can take a look at fixing the doit workflow using your suggestions.

**Comment by bollwyvl** [comment]
Made some more windows path concessions on #563: please have a look at current `main`.

**Comment by bollwyvl** [comment]
> please have a look

you may wish to belay that until #566 lands, as we found a few issues with #563

**Comment by danielemoroni** [comment]
thank you, I can now pass beyond env:lite:extensions, and I get errors at docs:app:build, copying only the last part of the log:

> .  pre_build:federated_extensions:extract:wheel:@jupyterlite/p5-kernel-extension
TaskError - taskid:pre_build:federated_extensions:extract:wheel:@jupyterlite/p5-kernel-extension
PythonAction Error
Traceback (most recent call last):
  File "C:\mf\envs\jupyterlite-dev\lib\site-packages\doit\action.py", line 437, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "C:\Users\DanieleMoroni\Documents\dev\jupyterlite\py\jupyterlite\src\jupyterlite\addons\federated_extensions.py", line 188, in _extract
    zf.extractall(td, members)
  File "C:\mf\envs\jupyterlite-dev\lib\zipfile.py", line 1633, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\mf\envs\jupyterlite-dev\lib\zipfile.py", line 1687, in _extract_member
    open(targetpath, "wb") as target:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\DANIEL~1\\AppData\\Local\\Temp\\tmpw3svaf97\\jupyterlite_p5_kernel-0.1.0a12.data\\data\\share\\jupyter\\labextensions\\@jupyterlite\\p5-kernel-extension\\static\\vendors-node_modules_css-loader_dist_runtime_api_js-node_modules_css-loader_dist_runtime_cssW-926fd9.34687ead919a402e3146.js'

Could this be because I failed to build . env:lite:deps:p5.ipynb too? Again, not an issue for me, but just to keep you and the community informed.

**Comment by bollwyvl** [comment]
that file name is too long for a stock windows system. there is a registry hack to "fix" it, for you, but yes, this would cause a problem for others downstream, and should be fixed. we could _consider_ degrading the experience if an individual extension failed to extract, i suppose, but seems like a bad precedent.

**Comment by jtpio** [comment]
Marking as "good first issue" in case someone on windows would want to give this a look.
