### ISSUE TITLE
voila extension tornado.web.HTTPError

### ISSUE THREAD

**Issue by eizanprime** [jupyterlite/jupyterlite#608]
I know that voila support is already on the road map, but as tornado based interactive widgets already work on jupyter lite I though that with some hack voila could be working.

Being able to make voila dashboard works with jupyter lite would make lite so easy..

I have tried installing the voila extension with jupyter lab, which did work for the front end part but the extension crashed when I try to open the tab

```
Traceback (most recent call last):
  File "/home/nicolas/miniconda3/envs/testvoilalite/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/home/nicolas/miniconda3/envs/testvoilalite/lib/python3.8/site-packages/tornado/web.py", line 2576, in get
    self.absolute_path = self.validate_absolute_path(self.root, absolute_path)
  File "/home/nicolas/miniconda3/envs/testvoilalite/lib/python3.8/site-packages/tornado/web.py", line 2778, in validate_absolute_path
    raise HTTPError(404)
tornado.web.HTTPError: HTTP 404: Not Found
``` 

Using the jupyter_server based extension was doomed to fail I guess, but as jupyter lab alread works with tordano is there any hack/patch that could make voila work ? 

Thank you so much.

**Comment by martinRenou** [comment]
> tornado based interactive widgets 

ipywidgets and custom widgets libraries are not tornado-based, if that's what you meant :)

Voila support will not be an easy task unfortunately, but it is on the roadmap!
