### ISSUE TITLE
Fails to fetch https://pypi.org/pypi/ipython/json due to CORS

### ISSUE THREAD

**Issue by ivanistheone** [jupyterlite/jupyterlite#636]
## Description

Today, JupyterLite notebooks and REPL are in a broken state due to a new CORS issue.

<img width="1246" alt="Screen Shot 2022-05-09 at 8 31 29 PM" src="https://user-images.githubusercontent.com/163966/167520027-e4596865-ec3d-4aee-9238-ff7e40767d0e.png">

found while testing new sympy shell at: https://www.sympy.org/en/shell.html
<img width="721" alt="failed load on Chrome" src="https://user-images.githubusercontent.com/163966/167519879-cabad6ad-3d95-4754-8f76-fd9282decb8a.png">

## Reproduce

1. Go to https://jupyterlite.github.io/demo/lab/index.html
2. Open a new notebook
3. Open the JS console to see errors

## Expected behavior

Commands to run `[*]` turn into `[1]`.

## Context

- JupyterLite version: current demo
- Operating System and version: macOS
- Browser and version: tried in latest Chrome or Firefox

full trace:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://pypi.org/pypi/ipython/json. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.

PythonError: Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 500, in eval_code_async
    await CodeRunner(
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 353, in run_async
    await coroutine
  File "<exec>", line 9, in <module>
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/site-packages/piplite/piplite.py", line 80, in install
    return await _MP_PACKAGE_MANAGER.install(requirements, ctx, keep_going)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 183, in install
    transaction = await self.gather_requirements(requirements, ctx, keep_going)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 173, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 280, in add_requirement
    metadata = await _get_pypi_json(req.name)
  File "/lib/python3.10/site-packages/piplite/piplite.py", line 72, in _get_pypi_json
    return await _MP_GET_PYPI_JSON(pkgname)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 86, in _get_pypi_json
    return json.loads(await fetch_string(url))
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 58, in fetch_string
    return await (await pyfetch(url, **kwargs)).string()
  File "/lib/python3.10/site-packages/pyodide/http.py", line 231, in pyfetch
    url, await _jsfetch(url, to_js(kwargs, dict_converter=Object.fromEntries))
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
JsException: TypeError: NetworkError when attempting to fetch resource.
[pyodide.js:15:35654](https://cdn.jsdelivr.net/pyodide/v0.20.0/full/pyodide.js)
```

**Comment by ivanistheone** [comment]
Seems to have been a transient issue. Everything works fine now. Sorry for noise.

**Comment by jtpio** [comment]
No problem, thanks for reporting here for reference in case this happens again in the future 👍
