### ISSUE TITLE
Issue with "Deploy JupyterLite on a standalone server or locally" docs

### ISSUE THREAD

**Issue by rickwierenga** [jupyterlite/jupyterlite#718]
## Description

I am following [this guide](https://jupyterlite.readthedocs.io/en/latest/quickstart/standalone.html#get-an-empty-jupyterlite-site).

`jupyter lite init` gives the following error:

```
...
static:unpack
.  init:static:unpack
lite:patch:_output/jupyter-lite.json
lite:patch:_output/lab/jupyter-lite.json
lite:patch:_output/repl/jupyter-lite.json
lite:patch:_output/retro/jupyter-lite.json
lite:patch:_output/retro/tree/jupyter-lite.json
lite:patch:_output/retro/edit/jupyter-lite.json
lite:patch:_output/retro/consoles/jupyter-lite.json
lite:patch:_output/retro/notebooks/jupyter-lite.json
lite:patch:_output/jupyter-lite.ipynb
lite:patch:_output/lab/jupyter-lite.ipynb
lite:patch:_output/repl/jupyter-lite.ipynb
lite:patch:_output/retro/jupyter-lite.ipynb
lite:patch:_output/retro/tree/jupyter-lite.ipynb
lite:patch:_output/retro/edit/jupyter-lite.ipynb
lite:patch:_output/retro/consoles/jupyter-lite.ipynb
lite:patch:_output/retro/notebooks/jupyter-lite.ipynb
[LiteBuildApp] WARNING | [lite] [translation] `jupyterlab_server` was not importable, cannot create translation data No module named 'jupyterlab_server'
translation:copy
.  build:lite:patch:_output/jupyter-lite.json
TaskError - taskid:build:lite:patch:_output/jupyter-lite.json
PythonAction Error
Traceback (most recent call last):
  File "/Users/rickwierenga/workspace/test/env/lib/python3.9/site-packages/doit/action.py", line 461, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/Users/rickwierenga/workspace/test/env/lib/python3.9/site-packages/jupyterlite/addons/base.py", line 223, in merge_one_jupyterlite
    out_path.write_text(json.dumps(config, **JSON_FMT), **UTF8)
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pathlib.py", line 1285, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors) as f:
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/rickwierenga/workspace/test/dist/_output/jupyter-lite.json'
```

## Reproduce

https://jupyterlite.readthedocs.io/en/latest/quickstart/standalone.html#get-an-empty-jupyterlite-site

## Expected behavior

An empty built site.

## Context

- JupyterLite version: latest
- Operating System and version: macOS 12.3.1 
- Browser and version: n/a

**Comment by rickwierenga** [comment]
Update: this appears to only be the case if running `jupyter lite build` after `jupyter lite init`. Just `jupyter lite build` works fine. I guess this is unexpected behavior. It is for me as a user.

**Comment by jtpio** [comment]
@rickwierenga do you know if this is still an issue?

I just tried the following commands in a new environment and it worked fine:

```shell
pip install jupyterlite-core
jupyter lite init
jupyter lite build
```

**Comment by SylvainCorlay** [comment]
I am having the same issue locally.

```
FileNotFoundError: [Errno 2] No such file or directory: '/home/sylvain/_output/dev/jupyterlite/xeus-nelson-kernel/docs/jupyter-lite.json'
```

**Comment by SylvainCorlay** [comment]
The issue that I have is that `jupyter lite build` will pick up any JupyterLab extensions in subdirectories of the current working directory.

So most typically, invoking `jupyter lite build` from one's home directory will fail as soon as you are working on JupyterLab extension in subdirectories of your home directory. The "fix" is to run `jupyter lite` in another empty directory.

I think that JupyterLite should merely look into standard jupyter paths for better reproducibility.

**Comment by jtpio** [comment]
> I think that JupyterLite should merely look into standard jupyter paths for better reproducibility.

By default it also gets them from `{sys.prefix}/share/jupyter/labextensions`: https://jupyterlite.readthedocs.io/en/latest/howto/configure/simple_extensions.html#build-the-jupyterlite-website

It could also get them from a well defined URL in `jupyter_lite_config.json`. I don't recall the CLI looking in subdirectories, but maybe it does (need to check the logic in https://github.com/jupyterlite/jupyterlite/blob/main/py/jupyterlite-core/jupyterlite_core/addons/federated_extensions.py).

**Comment by SylvainCorlay** [comment]
> By default it also gets them from {sys.prefix}/share/jupyter/labextensions: https://jupyterlite.readthedocs.io/en/latest/howto/configure/simple_extensions.html#build-the-jupyterlite-website

I meant also this directory as being standard.
