### ISSUE TITLE
micropip / piplite error when running scikit learn:  ValueError: Contents don't match hash

### ISSUE THREAD

**Issue by DerThorsten** [jupyterlite/jupyterlite#785]
I sometimes get the error below when running code llike:

```
import numpy as np
from sklearn.manifold import TSNE
X = np.array([[0, 0, 0], [0, 1, 1], [1, 0, 1], [1, 1, 1]])
X_embedded = TSNE(n_components=2, learning_rate='auto',
                   init='random', perplexity=3).fit_transform(X)
X_embedded.shape
```

```
index.html:1 Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 506, in eval_code_async
    await CodeRunner(
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 359, in run_async
    await coroutine
  File "<exec>", line 2, in <module>
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/site-packages/piplite/piplite.py", line 100, in _install
    return await _micropip.install(
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 575, in install
    await gather(*wheel_promises)
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 225, in install
    self.validate()
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 177, in validate
    raise ValueError("Contents don't match hash")
ValueError: Contents don't match hash

    at new_error (cdn.jsdelivr.net/pyodide/v0.21.2/full/pyodide.asm.js:10)
    at cdn.jsdelivr.net/pyodide/v0.21.2/full/pyodide.asm.wasm
    at cdn.jsdelivr.net/pyodide/v0.21.2/full/pyodide.asm.wasm
    at method_call_trampoline (cdn.jsdelivr.net/pyodide/v0.21.2/full/pyodide.asm.js:10)
    at cdn.jsdelivr.net/pyodide/v0.21.2/full/pyodide.asm.wasm
    at cdn.jsdelivr.net/pyodide/v0.21.2/full/pyodide.asm.wasm
    at cdn.jsdelivr.net/pyodide/v0.21.2/full/pyodide.asm.wasm
    at cdn.jsdelivr.net/pyodide/v0.21.2/full/pyodide.asm.wasm
    at cdn.jsdelivr.net/pyodide/v0.21.2/full/pyodide.asm.wasm
    at cdn.jsdelivr.net/pyodide/v0.21.2/full/pyodide.asm.wasm
    at cdn.jsdelivr.net/pyodide/v0.21.2/full/pyodide.asm.wasm
    at cdn.jsdelivr.net/pyodide/v0.21.2/full/pyodide.asm.wasm
    at cdn.jsdelivr.net/pyodide/v0.21.2/full/pyodide.asm.wasm
    at cdn.jsdelivr.net/pyodide/v0.21.2/full/pyodide.asm.wasm
    at cdn.jsdelivr.net/pyodide/v0.21.2/full/pyodide.asm.wasm
    at cdn.jsdelivr.net/pyodide/v0.21.2/full/pyodide.asm.wasm
    at cdn.jsdelivr.net/pyodide/v0.21.2/full/pyodide.asm.wasm
    at cdn.jsdelivr.net/pyodide/v0.21.2/full/pyodide.asm.wasm
    at Object.Module.callPyObjectKwargs (cdn.jsdelivr.net/pyodide/v0.21.2/full/pyodide.asm.js:10)
    at Object.Module.callPyObject (cdn.jsdelivr.net/pyodide/v0.21.2/full/pyodide.asm.js:10)
    at wrapper (cdn.jsdelivr.net/pyodide/v0.21.2/full/pyodide.asm.js:10)
    ```

**Comment by jtpio** [comment]
Thanks @DerThorsten for reporting.

This was also noticed recently on the pandas website: https://pandas.pydata.org/getting_started.html

Which was fixed in https://github.com/pandas-dev/pandas/pull/48329.

**Comment by jtpio** [comment]
Closing as I've not seen this one for a while now and might have been fixed at some point.

Feel free to reopen in https://github.com/jupyterlite/pyodide-kernel if the issue persists.
