### ISSUE TITLE
Loading demo in Chrome crashes due to fetching non-existent URL, apparently due to stale browser cache

### ISSUE THREAD

**Issue by jameshfisher** [jupyterlite/jupyterlite#969]
## Description

As of today, the hosted demo does not load for me, due to a 404 when initializing. This seems to _only_ happen in my specific Chrome instance, and so seems to be tied to some hidden stale browser state.

## Reproduce

0. Be me on my Chrome instance
1. Go to https://jupyterlite.github.io/demo/repl
2. Open JS console
3. See error:

```
Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 161, in _fetch_bytes
    return await fetch_bytes(self.url, fetch_kwargs)
  File "/lib/python3.10/site-packages/micropip/_compat_in_pyodide.py", line 30, in fetch_bytes
    result_bytes = await (await pyfetch(url, **kwargs)).bytes()
  File "/lib/python3.10/pyodide/http.py", line 185, in bytes
    self._raise_if_failed()
  File "/lib/python3.10/pyodide/http.py", line 112, in _raise_if_failed
    raise OSError(
OSError: Request for https://jupyterlite.github.io/demo/build/pypi/./pyolite-0.1.0b17-py3-none-any.whl failed with status 404: 
```

Indeed, https://jupyterlite.github.io/demo/build/pypi/./pyolite-0.1.0b17-py3-none-any.whl is a 404.

However, all other browser instances fetch https://jupyterlite.github.io/demo/build/pypi/./pyolite-0.1.0b18-py3-none-any.whl, which loads normally.

## Expected behavior

REPL loads normally.

If broken due to some stale state, clearing all site data should fix the problem.

## Context

This only started a few hours ago.

This does not happen in incognito, or any other browser.

The only way I found to fix the issue was to open the Network tab, check "Disable cache", then reload.

The following did NOT fix the issue:

* Ctrl-Shift-R ("hard refresh").
* Clearing site data in the Application > Storage tab.
* Unregistering service workers.
* Restarting browser.

- Operating System and version: Windows
- Browser and version: Chrome Version 109.0.5414.120 (Official Build) (64-bit)

**Comment by jameshfisher** [comment]
Its complaint seems valid, this is a 404: https://jupyterlite.github.io/demo/build/pypi/./pyolite-0.1.0b17-py3-none-any.whl

**Comment by jameshfisher** [comment]
Hmm, this however serves a file: `https://jupyterlite.github.io/demo/build/pypi/./pyolite-0.1.0b18-py3-none-any.whl`

**Comment by jameshfisher** [comment]
Okay, so, bizarrely:

* On my Firefox instance, it loads the `b18` URL, which works, and all is good.
* On my Chrome instance, it tries to load the `b17` URL, which then fails. This is even with a hard refresh.

**Comment by jameshfisher** [comment]
Even weirder:

* On Chrome, even after "Clear site data, including third-party cookies", it still loads the `b17` URL, which then fails
* On Chrome but in incognito mode, it loads the `b18` URL and works

So I think there's some very-well-hidden bit of stale state in my browser, which is telling it to load an out-of-date URL. But where is this state?!

**Comment by jameshfisher** [comment]
Also tried restarting the browser, and unregistering all service workers at chrome://serviceworker-internals/. No effect - still broken.

**Comment by jameshfisher** [comment]
Here's the full console log from the non-working browser:

```
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.
manifest.webmanifest:1 Manifest: property 'url' ignored, should be within scope of the manifest.
manifest.webmanifest:1 Manifest: property 'url' of 'shortcut' not present.
manifest.webmanifest:1 Manifest: property 'url' ignored, should be within scope of the manifest.
manifest.webmanifest:1 Manifest: property 'url' of 'shortcut' not present.
favicon.ico:1          GET https://jupyterlite.github.io/favicon.ico 404
remoteEntry.8a4c97071917cf84832f.js:1 Unsatisfied version 3.5.2 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/apputils (required ^4.0.0-alpha.11)
s @ remoteEntry.8a4c97071917cf84832f.js:1
(anonymous) @ remoteEntry.8a4c97071917cf84832f.js:1
(anonymous) @ remoteEntry.8a4c97071917cf84832f.js:1
643 @ remoteEntry.8a4c97071917cf84832f.js:1
(anonymous) @ remoteEntry.8a4c97071917cf84832f.js:1
g.f.consumes @ remoteEntry.8a4c97071917cf84832f.js:1
(anonymous) @ remoteEntry.8a4c97071917cf84832f.js:1
g.e @ remoteEntry.8a4c97071917cf84832f.js:1
./extension @ remoteEntry.8a4c97071917cf84832f.js:1
a @ remoteEntry.8a4c97071917cf84832f.js:1
r @ index.js:26
(anonymous) @ index.js:128
a @ index.js:121
await in a (async)
(anonymous) @ bootstrap.js:91
await in (anonymous) (async)
68653 @ bootstrap.js:65
v @ bootstrap:19
(anonymous) @ startup:4
(anonymous) @ bundle.js?_=cd5a1e6:1
remoteEntry.176149dcbfb677ea36fb.js:1 Unsatisfied version 6.0.2 of shared singleton module @jupyter-widgets/base (required ^1.0.4 || ^2 || ^3 || ^4)
l @ remoteEntry.176149dcbfb677ea36fb.js:1
(anonymous) @ remoteEntry.176149dcbfb677ea36fb.js:1
(anonymous) @ remoteEntry.176149dcbfb677ea36fb.js:1
591 @ remoteEntry.176149dcbfb677ea36fb.js:1
(anonymous) @ remoteEntry.176149dcbfb677ea36fb.js:1
b.f.consumes @ remoteEntry.176149dcbfb677ea36fb.js:1
(anonymous) @ remoteEntry.176149dcbfb677ea36fb.js:1
b.e @ remoteEntry.176149dcbfb677ea36fb.js:1
./extension @ remoteEntry.176149dcbfb677ea36fb.js:1
o @ remoteEntry.176149dcbfb677ea36fb.js:1
r @ index.js:26
(anonymous) @ index.js:128
a @ index.js:121
await in a (async)
(anonymous) @ bootstrap.js:91
await in (anonymous) (async)
68653 @ bootstrap.js:65
v @ bootstrap:19
(anonymous) @ startup:4
(anonymous) @ bundle.js?_=cd5a1e6:1
service-manager.ts:50 Registering new JupyterLite ServiceWorker https://jupyterlite.github.io/demo/service-worker-b2fb40a.js
index.js:73 JupyterLab extension jupyter-wren-syntax is activated!
service-manager.ts:52 JupyterLite ServiceWorker was sucessfully registered
index.ts:235 Kernel filesystem and JupyterLite contents will be synced
settingsplugin.ts:42 Settings failed to load for (@jupyterlab/cell-toolbar-extension:plugin) [{…}]
(anonymous) @ settingsplugin.ts:42
await in (anonymous) (async)
(anonymous) @ settingsplugin.ts:34
settingsplugin.ts:44 This may happen if {autoStart: false} in (@jupyterlab/cell-toolbar-extension:plugin) or if it is one of the deferredExtensions in page config.
(anonymous) @ settingsplugin.ts:44
await in (anonymous) (async)
(anonymous) @ settingsplugin.ts:34
settingsplugin.ts:42 Settings failed to load for (@jupyterlab/notebook-extension:panel) [{…}]
(anonymous) @ settingsplugin.ts:42
await in (anonymous) (async)
(anonymous) @ settingsplugin.ts:34
settingsplugin.ts:44 This may happen if {autoStart: false} in (@jupyterlab/notebook-extension:panel) or if it is one of the deferredExtensions in page config.
(anonymous) @ settingsplugin.ts:44
await in (anonymous) (async)
(anonymous) @ settingsplugin.ts:34
settingsplugin.ts:42 Settings failed to load for (@jupyterlab/csvviewer-extension:csv) [{…}]
(anonymous) @ settingsplugin.ts:42
await in (anonymous) (async)
(anonymous) @ settingsplugin.ts:34
settingsplugin.ts:44 This may happen if {autoStart: false} in (@jupyterlab/csvviewer-extension:csv) or if it is one of the deferredExtensions in page config.
(anonymous) @ settingsplugin.ts:44
await in (anonymous) (async)
(anonymous) @ settingsplugin.ts:34
settingsplugin.ts:42 Settings failed to load for (@jupyterlab/csvviewer-extension:tsv) [{…}]
(anonymous) @ settingsplugin.ts:42
await in (anonymous) (async)
(anonymous) @ settingsplugin.ts:34
settingsplugin.ts:44 This may happen if {autoStart: false} in (@jupyterlab/csvviewer-extension:tsv) or if it is one of the deferredExtensions in page config.
(anonymous) @ settingsplugin.ts:44
await in (anonymous) (async)
(anonymous) @ settingsplugin.ts:34
settingsplugin.ts:42 Settings failed to load for (@jupyterlab/filebrowser-extension:widget) [{…}]
(anonymous) @ settingsplugin.ts:42
await in (anonymous) (async)
(anonymous) @ settingsplugin.ts:34
settingsplugin.ts:44 This may happen if {autoStart: false} in (@jupyterlab/filebrowser-extension:widget) or if it is one of the deferredExtensions in page config.
(anonymous) @ settingsplugin.ts:44
await in (anonymous) (async)
(anonymous) @ settingsplugin.ts:34
settingsplugin.ts:42 Settings failed to load for (@jupyterlab/fileeditor-extension:plugin) [{…}]
(anonymous) @ settingsplugin.ts:42
await in (anonymous) (async)
(anonymous) @ settingsplugin.ts:34
settingsplugin.ts:44 This may happen if {autoStart: false} in (@jupyterlab/fileeditor-extension:plugin) or if it is one of the deferredExtensions in page config.
(anonymous) @ settingsplugin.ts:44
await in (anonymous) (async)
(anonymous) @ settingsplugin.ts:34
settingsplugin.ts:42 Settings failed to load for (@jupyterlab/htmlviewer-extension:plugin) [{…}]
(anonymous) @ settingsplugin.ts:42
await in (anonymous) (async)
(anonymous) @ settingsplugin.ts:34
settingsplugin.ts:44 This may happen if {autoStart: false} in (@jupyterlab/htmlviewer-extension:plugin) or if it is one of the deferredExtensions in page config.
(anonymous) @ settingsplugin.ts:44
await in (anonymous) (async)
(anonymous) @ settingsplugin.ts:34
index.ts:65 Pyolite contents will be synced with Jupyter Contents
pyodide.asm.js:10 Loading micropip, pyparsing, packaging
pyodide.asm.js:10 Loaded pyparsing, packaging, micropip
pyodide.asm.js:10 Loading sqlite3
pyodide.asm.js:10 Loaded sqlite3
kernel.ts:49 Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 161, in _fetch_bytes
    return await fetch_bytes(self.url, fetch_kwargs)
  File "/lib/python3.10/site-packages/micropip/_compat_in_pyodide.py", line 30, in fetch_bytes
    result_bytes = await (await pyfetch(url, **kwargs)).bytes()
  File "/lib/python3.10/pyodide/http.py", line 185, in bytes
    self._raise_if_failed()
  File "/lib/python3.10/pyodide/http.py", line 112, in _raise_if_failed
    raise OSError(
OSError: Request for https://jupyterlite.github.io/demo/build/pypi/./pyolite-0.1.0b17-py3-none-any.whl failed with status 404: 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/_pyodide/_base.py", line 531, in eval_code_async
    await CodeRunner(
  File "/lib/python3.10/_pyodide/_base.py", line 359, in run_async
    await coroutine
  File "<exec>", line 4, in <module>
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/site-packages/piplite/piplite.py", line 102, in _install
    return await _micropip.install(
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 573, in install
    await transaction.gather_requirements(requirements)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 333, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 340, in add_requirement
    return await self.add_requirement_inner(Requirement(req))
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 448, in add_requirement_inner
    await self.add_wheel(wheel, req.extras)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 461, in add_wheel
    await wheel.download(self.fetch_kwargs)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 177, in download
    data = await self._fetch_bytes(fetch_kwargs)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 169, in _fetch_bytes
    raise ValueError(
ValueError: Can't fetch wheel from 'https://jupyterlite.github.io/demo/build/pypi/./pyolite-0.1.0b17-py3-none-any.whl'. One common reason for this is when the server blocks Cross-Origin Resource Sharing (CORS). Check if the server is sending the correct 'Access-Control-Allow-Origin' header.

    at new_error (pyodide.asm.js:10:179954)
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at method_call_trampoline (pyodide.asm.js:10:229349)
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at Module.callPyObjectKwargs (pyodide.asm.js:10:123403)
    at Module.callPyObject (pyodide.asm.js:10:123781)
    at wrapper (pyodide.asm.js:10:219389)
deserialize @ comlink.mjs:57
b @ comlink.mjs:272
await in b (async)
g @ kernel.ts:28
create @ index.ts:70
await in create (async)
startNew @ kernels.ts:141
startNew @ sessions.ts:108
(anonymous) @ index.ts:442
route @ router.ts:89
await in route (async)
fetch @ app.ts:77
e.handleRequest @ serverconnection.ts:313
e.makeRequest @ serverconnection.ts:145
t.startSession @ restapi.ts:107
startNew @ manager.ts:161
_changeKernel @ sessioncontext.tsx:895
changeKernel @ sessioncontext.tsx:689
await in changeKernel (async)
selectKernel @ sessioncontext.tsx:1316
await in selectKernel (async)
(anonymous) @ panel.ts:90
Promise.then (async)
D @ panel.ts:88
B @ index.ts:251
await in B (async)
execute @ index.ts:492
e.execute @ index.ts:437
(anonymous) @ index.ts:149
Promise.then (async)
activate @ index.ts:148
(anonymous) @ index.ts:329
```

**Comment by jameshfisher** [comment]
Here's the full console log from the working browser:

```
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.
manifest.webmanifest:1 Manifest: property 'url' ignored, should be within scope of the manifest.
manifest.webmanifest:1 Manifest: property 'url' of 'shortcut' not present.
manifest.webmanifest:1 Manifest: property 'url' ignored, should be within scope of the manifest.
manifest.webmanifest:1 Manifest: property 'url' of 'shortcut' not present.
remoteEntry.8a4c97071917cf84832f.js:1 Unsatisfied version 3.5.2 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/apputils (required ^4.0.0-alpha.11)
s @ remoteEntry.8a4c97071917cf84832f.js:1
(anonymous) @ remoteEntry.8a4c97071917cf84832f.js:1
(anonymous) @ remoteEntry.8a4c97071917cf84832f.js:1
643 @ remoteEntry.8a4c97071917cf84832f.js:1
(anonymous) @ remoteEntry.8a4c97071917cf84832f.js:1
g.f.consumes @ remoteEntry.8a4c97071917cf84832f.js:1
(anonymous) @ remoteEntry.8a4c97071917cf84832f.js:1
g.e @ remoteEntry.8a4c97071917cf84832f.js:1
./extension @ remoteEntry.8a4c97071917cf84832f.js:1
a @ remoteEntry.8a4c97071917cf84832f.js:1
r @ index.js:26
(anonymous) @ index.js:128
a @ index.js:121
await in a (async)
(anonymous) @ bootstrap.js:91
await in (anonymous) (async)
68653 @ bootstrap.js:65
v @ bootstrap:19
(anonymous) @ startup:4
(anonymous) @ bundle.js?_=cd5a1e6:1
remoteEntry.176149dcbfb677ea36fb.js:1 Unsatisfied version 6.0.2 of shared singleton module @jupyter-widgets/base (required ^1.0.4 || ^2 || ^3 || ^4)
l @ remoteEntry.176149dcbfb677ea36fb.js:1
(anonymous) @ remoteEntry.176149dcbfb677ea36fb.js:1
(anonymous) @ remoteEntry.176149dcbfb677ea36fb.js:1
591 @ remoteEntry.176149dcbfb677ea36fb.js:1
(anonymous) @ remoteEntry.176149dcbfb677ea36fb.js:1
b.f.consumes @ remoteEntry.176149dcbfb677ea36fb.js:1
(anonymous) @ remoteEntry.176149dcbfb677ea36fb.js:1
b.e @ remoteEntry.176149dcbfb677ea36fb.js:1
./extension @ remoteEntry.176149dcbfb677ea36fb.js:1
o @ remoteEntry.176149dcbfb677ea36fb.js:1
r @ index.js:26
(anonymous) @ index.js:128
a @ index.js:121
await in a (async)
(anonymous) @ bootstrap.js:91
await in (anonymous) (async)
68653 @ bootstrap.js:65
v @ bootstrap:19
(anonymous) @ startup:4
(anonymous) @ bundle.js?_=cd5a1e6:1
service-manager.ts:50 Registering new JupyterLite ServiceWorker https://jupyterlite.github.io/demo/service-worker-b2fb40a.js
index.js:73 JupyterLab extension jupyter-wren-syntax is activated!
service-manager.ts:52 JupyterLite ServiceWorker was sucessfully registered
index.ts:235 Kernel filesystem and JupyterLite contents will be synced
settingsplugin.ts:42 Settings failed to load for (@jupyterlab/fileeditor-extension:plugin) [{…}]
(anonymous) @ settingsplugin.ts:42
await in (anonymous) (async)
(anonymous) @ settingsplugin.ts:34
settingsplugin.ts:44 This may happen if {autoStart: false} in (@jupyterlab/fileeditor-extension:plugin) or if it is one of the deferredExtensions in page config.
(anonymous) @ settingsplugin.ts:44
await in (anonymous) (async)
(anonymous) @ settingsplugin.ts:34
settingsplugin.ts:42 Settings failed to load for (@jupyterlab/htmlviewer-extension:plugin) [{…}]
(anonymous) @ settingsplugin.ts:42
await in (anonymous) (async)
(anonymous) @ settingsplugin.ts:34
settingsplugin.ts:44 This may happen if {autoStart: false} in (@jupyterlab/htmlviewer-extension:plugin) or if it is one of the deferredExtensions in page config.
(anonymous) @ settingsplugin.ts:44
await in (anonymous) (async)
(anonymous) @ settingsplugin.ts:34
settingsplugin.ts:42 Settings failed to load for (@jupyterlab/cell-toolbar-extension:plugin) [{…}]
(anonymous) @ settingsplugin.ts:42
await in (anonymous) (async)
(anonymous) @ settingsplugin.ts:34
settingsplugin.ts:44 This may happen if {autoStart: false} in (@jupyterlab/cell-toolbar-extension:plugin) or if it is one of the deferredExtensions in page config.
(anonymous) @ settingsplugin.ts:44
await in (anonymous) (async)
(anonymous) @ settingsplugin.ts:34
settingsplugin.ts:42 Settings failed to load for (@jupyterlab/csvviewer-extension:csv) [{…}]
(anonymous) @ settingsplugin.ts:42
await in (anonymous) (async)
(anonymous) @ settingsplugin.ts:34
settingsplugin.ts:44 This may happen if {autoStart: false} in (@jupyterlab/csvviewer-extension:csv) or if it is one of the deferredExtensions in page config.
(anonymous) @ settingsplugin.ts:44
await in (anonymous) (async)
(anonymous) @ settingsplugin.ts:34
settingsplugin.ts:42 Settings failed to load for (@jupyterlab/csvviewer-extension:tsv) [{…}]
(anonymous) @ settingsplugin.ts:42
await in (anonymous) (async)
(anonymous) @ settingsplugin.ts:34
settingsplugin.ts:44 This may happen if {autoStart: false} in (@jupyterlab/csvviewer-extension:tsv) or if it is one of the deferredExtensions in page config.
(anonymous) @ settingsplugin.ts:44
await in (anonymous) (async)
(anonymous) @ settingsplugin.ts:34
settingsplugin.ts:42 Settings failed to load for (@jupyterlab/filebrowser-extension:widget) [{…}]
(anonymous) @ settingsplugin.ts:42
await in (anonymous) (async)
(anonymous) @ settingsplugin.ts:34
settingsplugin.ts:44 This may happen if {autoStart: false} in (@jupyterlab/filebrowser-extension:widget) or if it is one of the deferredExtensions in page config.
(anonymous) @ settingsplugin.ts:44
await in (anonymous) (async)
(anonymous) @ settingsplugin.ts:34
settingsplugin.ts:42 Settings failed to load for (@jupyterlab/notebook-extension:panel) [{…}]
(anonymous) @ settingsplugin.ts:42
await in (anonymous) (async)
(anonymous) @ settingsplugin.ts:34
settingsplugin.ts:44 This may happen if {autoStart: false} in (@jupyterlab/notebook-extension:panel) or if it is one of the deferredExtensions in page config.
(anonymous) @ settingsplugin.ts:44
await in (anonymous) (async)
(anonymous) @ settingsplugin.ts:34
index.ts:65 Pyolite contents will be synced with Jupyter Contents
pyodide.asm.js:10 Loading micropip, pyparsing, packaging
pyodide.asm.js:10 Loaded pyparsing, packaging, micropip
pyodide.asm.js:10 Loading sqlite3
pyodide.asm.js:10 Loaded sqlite3
pyodide.asm.js:10 Loading pygments, decorator, jedi, parso, six
pyodide.asm.js:10 Loaded six, decorator, parso, pygments, jedi
```

**Comment by jameshfisher** [comment]
Aha, I was able to "fix" this by checking "Disable cache" in the Network tab. So it is indeed a caching issue, but with what ...

**Comment by jameshfisher** [comment]
Unfortunately, I think "Disable cache" has permanently cleared the cache, so I now can't reproduce the problem. But I would guess the issue is due to caching on one of these other domains that it loads from:

```
jupyterlite.github.io
cdn.jsdelivr.net
pypi.org
files.pythonhosted.org
```

**Comment by jtpio** [comment]
Thanks @jameshfisher for reporting and all the details :+1: 

This sounds similar to the caching issue mentioned in https://github.com/jupyterlite/jupyterlite/issues/815.
