### ISSUE TITLE
Browser storage settings for volatile memory storage not updating with an overrides.json

### ISSUE THREAD

**Issue by savakarrohan** [jupyterlite/jupyterlite#991]
## Description
I am attempting to change the storage to a volatile memory type as described by the [browser storage example](https://jupyterlite.readthedocs.io/en/latest/howto/configure/storage.html#volatile-memory-storage). In order to do so i have created a `overrides.json` file in the root of the jupyter-lite build site as follows
```
{
"@jupyterlab/apputils-extension:themes":{
      "theme": "theme01"
  },
      "enableMemoryStorage": true,
      "contentsStorageDrivers":["memoryStorageDriver"],
      "settingsStorageDrivers":["memoryStorageDriver"]
}
```
On running the site through `jupyter lite serve` or through `http.serve()` it is clear that a new notebook formed is not volatile. That is the notebook persists even after a refresh

## What is working right now
My workarounds right now
1. I bypass this problem by copying the contents of `overrides.json` to the appropriate location in the `jupyterlite-json` just above `"fullLabextensionsUrl": "./extensions",`

## My attempts
1. I have tried adding a `jupyter-lite.json` instead of an `overrides.json` which appears to not work.
2. Does the ordering matter? sometimes an error is thrown such as 
```
TaskError - taskid:post_build:settings:patch:overrides:None
PythonAction Error
Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\envs\jup02\lib\site-packages\doit\action.py", line 461, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "C:\ProgramData\miniconda3\envs\jup02\lib\site-packages\jupyterlite\addons\settings.py", line 120, in patch_one_overrides
    overrides[k].update(v)
AttributeError: 'bool' object has no attribute 'update'
```

## Reproduce

1. New `jupyterlite init`
3. create `overrides.json` with data as mentioned
4. `build` or `serve` site

## Expected behavior
I expect the `overrides.json` file to configure the settings correctly, which is tested by creating a pyodide notebook on the served site and saving it with a random name. Upon a refresh, the notebook previously created should disappear.

## Context
volatile storage
I have taken care to clear caches and use the incognito browser.

- JupyterLite version:0.1.0b18
- Operating System and version:Windows
- Browser and version:Edge

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by jtpio** [comment]
Thanks @savakarrohan for the report.

This setting is used for the SymPy online shell in case you would like to have a look for reference: https://github.com/sympy/live/blob/f73ff1ba47cc4a2e22593e73d15b39240b002ff1/jupyter-lite.json#L10-L12
